package:
  # pure python
  name: pyreadline
  version: "2.0"

source:
  fn:  pyreadline-2.0.zip
  url: https://pypi.python.org/packages/source/p/pyreadline/pyreadline-2.0.zip
  md5: 87b15f18deff1db76e9d37149a2b027b

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://pypi.python.org/pypi/pyreadline
  license: BSD
  summary: python implmementation of GNU readline
