{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: qt-with-src
  version: "4.8.6{{toolset.suffix}}"

source:
  git_url: https://github.com/qtproject/qt
  #git_tag: v4.8.6 # 682ed9df439481e1f8e8651c4aa06f1b455a2080
  # FIXME: this commit is inconsistent: it claims to be version 4.8.7,
  #        but behaves like version 4.8.6
  git_tag: 445d29dbb8135944ff3a9283b7622de75d68e747

  patches:
    # This patch fixes ilastik crashes on OSX due to an ill-shaped ellipse
    - patches/qt4-osx-draw-ellipse.patch  # [osx]

    # This patch fixes crashes with modal dialogs on OSX:
    # https://bugreports.qt.io/secure/attachment/46537/QTBUG-40585-Rev3.patch
    - patches/QTBUG-40585-Rev3.patch  # [osx]

build:
  features:
    - {{toolset.short}}
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    - perl     active_state            # [win]
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}
    - zlib     *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}
    - zlib     *{{toolset.suffix}}
