package:
  # pure python
  name: babel
  version: "2.0"

source:
  fn:  Babel-2.0.tar.gz
  url: https://pypi.python.org/packages/source/B/Babel/Babel-2.0.tar.gz
  md5: 62917719897a81e22dcaa3b17eeb11d8

requirements:
  build:
    - python
    - pytz
    - setuptools

  run:
    - python
    - pytz

about:
  home: https://pypi.python.org/pypi/Babel
  license: BSD
  summary: Internationalization utilities
