{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
    name: feature_selection
    version: "1.0{{toolset.suffix}}"

source:
    git_url: https://github.com/ilastik/ilastik-feature-selection
    git_tag: HEAD

build:
  features:
    - {{toolset.short}}
  number: 1
  string: {{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - cython  *{{toolset.suffix}}
    - scikit-learn *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - scikit-learn *{{toolset.suffix}}

about:
    home: https://bitbucket.org/FabianIsensee/feature_selection_clean
    license: MIT
    summary: feature selection library

