{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: hdf5
  version: "1.8.12{{toolset.suffix}}"

source:
    fn:  hdf5-1.8.12.tar.gz
    md5: d804802feb99b87fc668a90e6fa34411
    url: http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.12/src/hdf5-1.8.12.tar.gz
    
    # FIXME: hdf5 1.8.15 needs cmake >=3.1 
    # fn:  hdf5-1.8.15-patch1.tar.bz2
    # md5: 3c0d7a8c38d1abc7b40fc12c1d5f2bb8
    # url: http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.bz2

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - zlib    *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - zlib    *{{toolset.suffix}}

about:
  home: https://www.hdfgroup.org/HDF5/
  license: HDF5 license (similar to BSD)
  summary: HDF5 data format I/O
