package:
  # pure python
  name: docutils
  version: "0.12"

source:
  # fn:  docutils-0.10.tar.gz
  # url: https://pypi.python.org/packages/source/d/docutils/docutils-0.10.tar.gz
  # md5: d8d4660c08302c791b2d71a155a2f4bc
  fn:  docutils-0.12.tar.gz
  url: https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz
  md5: 4622263b62c5c771c03502afa3157768

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://pypi.python.org/pypi/docutils
  license: public domain, BSD, PSF
  summary: Python Documentation Utilities
