{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all ilastik dependencies and downloading the ilastik-meta repo."

package:
  name: ilastik-everything
  version: "" # build.sh will generate a __conda_version__.txt file

build:
  track_features:
    - {{toolset.short}}
  features:
    - {{toolset.short}}
  number: 1

requirements:
  build:
    - {{toolset.build_requirement}}
    - ilastik-everything-but-tracking # <-- Needed just to print ilastik.__version__ into __conda_version__.txt
    - ilastik-deps-tracking            *{{toolset.suffix}}
    - ilastik-versions                 *{{toolset.suffix}}

  run:
    - ilastik-everything-but-tracking  *{{toolset.suffix}}
    - ilastik-deps-tracking            *{{toolset.suffix}}
    - ilastik-versions                 *{{toolset.suffix}}

test:
  requires:
    - nose
    
  imports:
    - lazyflow
    - volumina
    - ilastik
