{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all ilastik dependencies and downloading the ilastik-meta repo."

package:
  name: ilastik-everything
  # build scripts will prepend actual version via a __conda_version__.txt file
  version: "{{toolset.suffix}}"

build:
  track_features:
    - {{toolset.short}}
  features:
    - {{toolset.short}}
  number: 1

requirements:
  build:
    - {{toolset.build_requirement}}
    - ilastik-everything-but-tracking 
    - ilastik-deps-tracking            *{{toolset.suffix}}
    - ilastik-versions                 *{{toolset.suffix}}

  run:
    - ilastik-everything-but-tracking  *{{toolset.suffix}}
    - ilastik-deps-tracking            *{{toolset.suffix}}
    - ilastik-versions                 *{{toolset.suffix}}

test:
  requires:
    - nose
    
  imports:
    - lazyflow
    - volumina
    - ilastik
