{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

about:
  summary: "Configure MinGW as a subtool of Visual Studio (needed to compile packages that MSVC can't handle, e.g. Fortran sources)"

package:
  name: mingw-for-msvc
  version: "4.7.2"

build:
  track_features:
    - {{toolset.short}}
  features:
    - {{toolset.short}}
  number: 1
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - emulate_c99   *{{toolset.suffix}}   # [win]

  run:
    - {{toolset.run_requirement}}
    - emulate_c99   *{{toolset.suffix}}   # [win]
