{% import TOOLSET_CONFIG as toolset %}

package:
  name: ilastik-exe
  version: "1.0{{toolset.suffix}}"

# source is in recipe dir

requirements:
  build:
    - {{toolset.build_requirement}}
    
  run:
    - {{toolset.run_requirement}}
