{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: ilastik-exe
  version: "1.0{{toolset.suffix}}"

# source is in recipe dir

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    
  run:
    - {{toolset.run_requirement}}
