package:
  # pure python
  name: mock
  version: "1.3.0"

source:
  fn:  mock-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz
  md5: 73ee8a4afb3ff4da1b4afa287f39fdeb

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://pypi.python.org/pypi/mock
  license: BSD
  summary: Rolling backport of unittest.mock for all Pythons
