{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: iconv
  version: "1.14{{toolset.suffix}}"

source:
  fn:  libiconv-1.14.tar.gz
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz
  md5: e34509b1623cec449dfeb73d7ce9c6c6

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - mingw-for-msvc-build           # [win]

  run:
    - mingw-for-msvc                 # [win]

about:
  home: http://www.gnu.org/software/libiconv/
  license: GPL v3
  summary: character encoding conversion library
