# Credits to jeanconn for the package https://binstar.org/jeanconn/fftw
package:
    name: fftw
    version: "3.3.4"

source:
    fn: fftw-3.3.4.tar.gz
    url: http://www.fftw.org/fftw-3.3.4.tar.gz
    md5: 2edab8c06b24feeb3b82bbb3ebf3e7b3


{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  number: 1
  detect_binary_files_with_prefix: true
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

# Note: tests are run when building the package, they are not accessible
# in the installed package.

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - python                         # [win]  (needed to download the Visual Studio project)

  run:
    - visual-studio {{ vc_version }} # [win]

about:
    home: http://fftw.org
    license: GNU General Public License (GPL)
    summary: 'The fastest Fourier transform in the west.'
