package:
  name: pillow
  version: "2.9.0"

source:
  fn:  Pillow-2.9.0.tar.gz
  url: https://pypi.python.org/packages/source/P/Pillow/Pillow-2.9.0.tar.gz
  md5: 46f1729ece27981d54ec543ad5b37d14

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - python                         # [unix]
    - python   2.7.10                # [win]
    - numpy    1.7.0                 # [win]
    - jpeg     8d                    # [unix]
    - jpeg     1.2.1                 # [win]
    - libtiff  4.0*                  # [unix]
    - libtiff  4.0.1                 # [win]
    - libpng   1.6.17                # [unix]
    - libpng   1.5.13                # [win]
    - freetype
    - setuptools

  run:
    - visual-studio {{ vc_version }} # [win]
    - python                         # [unix]
    - python   2.7.10                # [win]
    - numpy    1.7.0                 # [win]
    - jpeg     8d                    # [unix]
    - jpeg     1.2.1                 # [win]
    - libtiff  4.0*                  # [unix]
    - libtiff  4.0.1                 # [win]
    - libpng   1.6.17                # [unix]
    - libpng   1.5.13                # [win]
    - freetype

about:
  home: https://pypi.python.org/pypi/Pillow
  license: Standard PIL License (similar to BSD)
  summary: Python Imaging Library (Fork)

