{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: pil
  version: "1.1.7{{toolset.suffix}}"

source:
  fn:  Imaging-1.1.7.tar.gz
  url: http://effbot.org/downloads/Imaging-1.1.7.tar.gz
  md5: fc14a54e1ce02a0225be8854bfba478e

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    # NOTE: PIL's support for TIFF is labeled experimental and commented out
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}

about:
  home: https://pypi.python.org/pypi/PIL
  license: old Python license (MIT style)
  summary: Python Imaging Library
