{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: itk-seg-conv-only
  version: "4.6.1{{toolset.suffix}}"

source:
  url: http://iweb.dl.sourceforge.net/project/itk/itk/4.6/InsightToolkit-4.6.1.tar.gz
  fn: InsightToolkit-4.6.1.tar.gz
  md5: 2c84eae50ab2452cdad32aaadced3c37

build:
  features:
    - {{toolset.short}}
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - hdf5     1.8.14                  # [unix]
    - hdf5     1.8.*{{toolset.suffix}} # [win]
    - zlib     *{{toolset.suffix}}

  run:
    # - libgcc                         # [unix]
    - {{toolset.run_requirement}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - hdf5     1.8.14                  # [unix]
    - hdf5     1.8.*{{toolset.suffix}} # [win]
    - zlib     *{{toolset.suffix}}

about:
  home: http://itk.org
  license: Apache 2.0
  summary: This conda package builds a small subset of ITK modules.  See build.sh for details.
