package:
  name: itk-seg-conv-only
  version: 4.6.1

source:
  url: http://superb-sea2.dl.sourceforge.net/project/itk/itk/4.6/InsightToolkit-4.6.1.tar.gz
  fn: InsightToolkit-4.6.1.tar.gz
  md5: 2c84eae50ab2452cdad32aaadced3c37

build:
  number: 6
  detect_binary_files_with_prefix: true

requirements:  
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - jpeg 8d
    - libtiff 4.0.6
    - libpng 1.6.17
    - hdf5 1.8.17
    - zlib

  run:
    - libgcc
    - zlib
    # Let these be optional at install time
    # - jpeg
    # - libtiff
    # - libpng
    # - hdf5 1.8.17

about:
  home: http://itk.org
  license: Apache 2.0
  summary: This conda package builds a small subset of ITK modules.  See build.sh for details.
