package:
  name: mlpack
  version: "1.0.8.99"

source:
  fn: mlpack-1.0.8.tar.gz
  url: http://www.mlpack.org/files/mlpack-1.0.8.tar.gz
  md5: 0331e12f2485b9d5d39c9d9dea618108

build:
  number: 7

requirements:
 build:
     - gcc 4.8.5 # [linux]
     - gcc 4.8.5 # [osx]
     - boost 1.55.0
     - armadillo 6.500.5
     - hdf5     1.8.16
     - libxml2
 run:
     - libgcc
     - boost 1.55.0
     - armadillo 6.500.5
     - hdf5     1.8.16
     - libxml2

about:
  home: http://www.mlpack.org/
  license: LGPL
  summary: a scalable c++ machine learning library
