{% import 'CONDA_ENVIRONMENT/toolset-info/config.yaml' as toolset %}

package:
  name: mlpack
  version: "1.0.8{{toolset.suffix}}"

source:
  fn: mlpack-1.0.8.tar.gz
  url: http://www.mlpack.org/files/mlpack-1.0.8.tar.gz
  md5: 0331e12f2485b9d5d39c9d9dea618108

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - mingw                            # [win] (needed for MSYS patch.exe)
    - boost  1.55.*{{toolset.suffix}}
    - armadillo   *{{toolset.suffix}}
    - libxml2     *{{toolset.suffix}}
    - hdf5    1.8.*{{toolset.suffix}}  # [win]
     
  run:
    - {{toolset.run_requirement}}
    # - libgcc                         # [unix]
    - boost  1.55.*{{toolset.suffix}}
    - armadillo   *{{toolset.suffix}}
    - libxml2     *{{toolset.suffix}}
    - hdf5    1.8.*{{toolset.suffix}}  # [win]

about:
  home: http://www.mlpack.org/
  license: LGPL
  summary: a scalable c++ machine learning library
