package:
  name: mlpack
  version: "1.0.8"

source:
  fn: mlpack-1.0.8.tar.gz
  url: http://www.mlpack.org/files/mlpack-1.0.8.tar.gz
  md5: 0331e12f2485b9d5d39c9d9dea618108

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
 build:
     - gcc 4.8.5.99 # [linux]
     - gcc 4.8.2 # [osx]
     - boost 1.55.0
     - armadillo
     - libxml2
 run:
     - libgcc
     - boost 1.55.0
     - armadillo
     - libxml2

about:
  home: http://www.mlpack.org/
  license: LGPL
  summary: a scalable c++ machine learning library
