package:
  # pure python
  name: simplegeneric
  version: "0.8.1"

source:
  fn:  simplegeneric-0.8.1.zip
  url: https://pypi.python.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.zip
  md5: f9c1fab00fd981be588fc32759f474e3

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://pypi.python.org/pypi/simplegeneric
  license: Zope Public License
  summary: Simple generic functions

