package:
  name: neuroproof 
  version: "1.2.1"
  
source:
  git_url: git://github.com/janelia-flyem/NeuroProof.git
  git_tag: f8808af80f02ced1c5ada2131b04497a6bb53789 # 2015-11-10

build:
  number: 13
  string: 13_gf8808af
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.5
    - python
    - jsoncpp
    - vigra
    - libdvid-cpp
    - vtk         5.10.1.99
    - hdf5        1.8.14
    - qt          4.8.6.99 # [osx]
    - qt          4.8*     # [linux]
    - opencv      2.4.10.1
    
  run:
    - libgcc
    - python
    - jsoncpp
    - vigra
    - libdvid-cpp
    - vtk         5.10.1.99
    - hdf5        1.8.14
    - qt          4.8.6.99 # [osx]
    - qt          4.8*     # [linux]
    - opencv      2.4.10.1

about:
  home: http://github.com/janelia-flyem/NeuroProof.git
  license: BSD (3-clause)
  summary: C++ library for image segmentation and analysis 
