package:
  name: neuroproof 
  version: "1.1"
  
source:
  git_url: git://github.com/janelia-flyem/NeuroProof.git
  git_tag: 8210cd378365fc1824d8ef2b3426238ee50c6820 # 2015-09-15

build:
  number: 12
  string: 12_g8210cd3
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.5
    - python
    - jsoncpp
    - vigra
    - libdvid-cpp
    - vtk         5.10.1.99
    - hdf5        1.8.14
    - qt          4.8.6.99 # [osx]
    - qt          4.8*     # [linux]
    - opencv      2.4.10.1
    
  run:
    - libgcc
    - python
    - jsoncpp
    - vigra
    - libdvid-cpp
    - vtk         5.10.1.99
    - hdf5        1.8.14
    - qt          4.8.6.99 # [osx]
    - qt          4.8*     # [linux]
    - opencv      2.4.10.1

about:
  home: http://github.com/janelia-flyem/NeuroProof.git
  license: BSD (3-clause)
  summary: C++ library for image segmentation and analysis 
