{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: tifffile
  version: "0.4.1{{toolset.suffix}}"

source:
  git_url: git://github.com/ilastik/tifffile.git
  git_tag: 05b51f398b2c18eacf9dce674631707763f7e94e

build:
  features:
    - {{toolset.short}}
  number: 1

requirements:
  build:
    - python 2.7.*|>=3.4              # [unix]
    - python 2.7.*{{toolset.suffix}}  # [win]
    # - numpy >=1.8.2,*{{toolset.suffix}}
    - numpy >=1.8.2                   # [unix]
    - numpy  1.7.*{{toolset.suffix}}  # [win]

  run:
    - python 2.7.*{{toolset.suffix}}  # [win]
    # - numpy >=1.8.2,*{{toolset.suffix}}
    - numpy >=1.8.2                   # [unix]
    - numpy  1.7.*{{toolset.suffix}}  # [win]

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD License
  summary: 'Read and write image data from and to TIFF files.'

