{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}


package:
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","") %}

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

  name: tifffile
#  version: {{tagged_version}}
  version: "0.4.1post2{{toolset.suffix}}"

source:
  git_url: git://github.com/ilastik/tifffile
  git_tag: 7c3bb9e12bbd4420d55cb0515132da1957b89b85 # # Branch 'ilastik-devel' (v0.4.post2)

build:
  features:
    - {{toolset.short}}
  number: 0
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - python 2.7.*|>=3.4                # [unix]
    - python 2.7.*{{toolset.suffix}}    # [win]
    # - numpy >=1.8.2,*{{toolset.suffix}}
    - numpy >=1.8.2                     # [unix]
    - numpy >=1.10,*{{toolset.suffix}}  # [win]
    - setuptools

  run:
    - python 2.7.*{{toolset.suffix}}    # [win]
    # - numpy >=1.8.2,*{{toolset.suffix}}
    - numpy >=1.8.2                     # [unix]
    - numpy >=1.10,*{{toolset.suffix}}  # [win]

# test:
  # imports:
    # - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD License
  summary: 'Read and write image data from and to TIFF files.'

