package:
  name: tifffile
  version: "0.4.1"

source:
  git_url: git://github.com/ilastik/tifffile.git
  git_tag: 05b51f398b2c18eacf9dce674631707763f7e94e

build:
  {% set build_num = 2 %}
  number: {{ build_num }}
  
  #
  # We use NPY_VER here: You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: "np{{ environ.get('NPY_VER', '-NPY_VER-UNDEFINED-').replace('.', '') }}\
           py{{ environ.get('PY_VER').replace('.', '') }}\
           _{{ build_num }}\
           _g{{ environ.get('GIT_FULL_HASH', '')[:7] }}"

  detect_binary_files_with_prefix: true

requirements:
  build:
    - python   2.7*
    - numpy    >=1.9,{{ environ.get('NPY_VER', '-NPY_VER-UNDEFINED-') }}*

  run:
    - python   {{ environ.get('PY_VER') }}*
    - numpy    {{ environ.get('NPY_VER') }}*

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD License
  summary: 'Read and write image data from and to TIFF files.'
