{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}


package:
  name: tifffile
  version: "0.9.2post1{{toolset.suffix}}"

source:
  git_url: git://github.com/ilastik/tifffile
  git_tag: cc9fb437fc124f3b4694075b070639dae3fddbed # Branch 'fix-modulo-attributes'

build:
  features:
    - {{toolset.short}}
  number: 0
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - python 2.7.*|>=3.4                # [unix]
    - python 2.7.*{{toolset.suffix}}    # [win]
    # - numpy >=1.8.2,*{{toolset.suffix}}
    - numpy >=1.8.2                     # [unix]
    - numpy >=1.10,*{{toolset.suffix}}  # [win]
    - setuptools

  run:
    - python 2.7.*{{toolset.suffix}}    # [win]
    # - numpy >=1.8.2,*{{toolset.suffix}}
    - numpy >=1.8.2                     # [unix]
    - numpy >=1.10,*{{toolset.suffix}}  # [win]

# test:
  # imports:
    # - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD License
  summary: 'Read and write image data from and to TIFF files.'

