{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: glog
  version: "0.3.4{{toolset.suffix}}"

source:
  git_url: https://github.com/google/glog.git
  git_tag: a66751870fb4e6184ac0a58303cb1f97e499f5fe

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - gflags  *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - gflags  *{{toolset.suffix}}

about:
  home: https://github.com/google/glog
  license: BSD
  summary: Google logging module
