{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: greenlet
  version: "0.4.7{{toolset.suffix}}"

source:
  fn:  greenlet-0.4.7.zip
  url: https://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.7.zip
  md5: c2333a8ff30fa75c5d5ec0e67b461086 

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}

about:
  home: https://pypi.python.org/pypi/greenlet
  license: MIT
  summary: Lightweight in-process concurrent programming


