package:
  name: colorama
  version: 0.3.3

source:
  fn:  colorama-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/c/colorama/colorama-0.3.3.tar.gz
  md5: a56b8dc55158a41ab3c89c4c8feb8824

requirements:
  build:
    - python 2.7.10 [win]

  run:
    - python 2.7.10 [win]

about:
  home: https://pypi.python.org/pypi/colorama
  license: BSD
  summary: Cross-platform colored terminal text.

