{% import TOOLSET_CONFIG as toolset %}

package:
  name: cython
  version: "0.23{{toolset.suffix}}"

source:
  fn:  Cython-0.23.tar.gz
  url: https://pypi.python.org/packages/source/C/Cython/Cython-0.23.tar.gz
  md5: 63d472d0a9b3b39b9651f7bf568bb4a5

requirements:
  build:
    - {{toolset.build_requirement}}
    - python    *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python    *{{toolset.suffix}}

about:
  home: http://cython.org/
  license: Apache Software License
  summary: The Cython compiler for writing C extensions for the Python language
