package:
  name: cython
  version: "0.23.99"

source:
  fn:  Cython-0.23.tar.gz
  url: https://pypi.python.org/packages/source/C/Cython/Cython-0.23.tar.gz
  md5: 63d472d0a9b3b39b9651f7bf568bb4a5

requirements:
  build:
    - visual-studio 11.0  # [win]
    - python        2.7.10

  run:
    - visual-studio 11.0  # [win]
    - python        2.7.10

about:
  home: http://cython.org/
  license: Apache Software License
  summary: The Cython compiler for writing C extensions for the Python language