package:
  name: cython
  version: "0.23"

source:
  fn:  Cython-0.23.tar.gz
  url: https://pypi.python.org/packages/source/C/Cython/Cython-0.23.tar.gz
  md5: 63d472d0a9b3b39b9651f7bf568bb4a5

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - python    2.7.*

  run:
    - visual-studio {{ vc_version }} # [win]
    - python    2.7.*

about:
  home: http://cython.org/
  license: Apache Software License
  summary: The Cython compiler for writing C extensions for the Python language
