package:
  name: gala
  version: "0.3.0"

source:
  git_url: https://github.com/janelia-flyem/gala
  git_tag: "v0.3.0"

build:
  {% set build_num = 2 %}
  number: {{ build_num }}
  string: "np{{ environ.get('NPY_VER', 'NPY_VER-UNDEFINED').replace('.', '') }}\
           py{{ environ.get('PY_VER').replace('.', '') }}\
           _{{ build_num }}"

requirements:
  build:
    - python >=2.7,<3|>=3.4,{{ environ.get('PY_VER') }}*
    - numpy >=1.7,{{ environ.get('NPY_VER', 'NPY_VER-UNDEFINED') }}*
    - scipy >=0.1
    - pillow >=2.5
    - networkx >=1.6
    - h5py >=1.5
    - cython >=0.17
    - scikit-learn >=0.15
    - matplotlib >=1.2
    - scikit-image >=0.9
    - viridis >=0.3

  run:
    - python {{ environ.get('PY_VER') }}*
    - numpy {{ environ.get('NPY_VER') }}*
    - scipy >=0.1
    - pillow >=2.5
    - networkx >=1.6
    - h5py >=1.5
    - cython >=0.17
    - scikit-learn >=0.15
    - matplotlib >=1.2
    - scikit-image >=0.9
    - viridis >=0.3

test:
  imports:
    - gala

about:
  home: https://github.com/janelia-flyem/gala
  license: BSD
  summary: 'Automatic segmentation of electron microscopy volumes'
