package:
  name: vigra
  version: "1.10"

source:
  #git_url: git://github.com/ukoethe/vigra.git
  #git_tag: 92a2fa1f85cdcd5e15f599f69414e84445701b38 # 2015-05-12

  git_url: git://github.com/stuarteberg/vigra.git
  git_tag: 5dde8872323b1e592c7fbae45235362b07a9a59a

build:
  script_env:
   - LD_LIBRARY_PATH
   - DYLD_LIBRARY_PATH

  number: 5
  string: 5dde887
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99 # [linux]
    - gcc 4.8.2 # [osx]
    - python
    - numpy
    - jpeg
    - libtiff
    - libpng
    - fftw
    - hdf5
    - boost 1.55.0
    - zlib
    - nose

  run:
    - libgcc
    - python
    - numpy
    - jpeg
    - libtiff
    - libpng
    - fftw
    - hdf5
    - boost 1.55.0
    - zlib
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

