package:
  name: vigra
  version: "1.10"

source:
  git_url: git://github.com/stuarteberg/vigra.git
  git_tag: HEAD

build:
  script_env:
   - LD_LIBRARY_PATH
   - DYLD_LIBRARY_PATH

  number: 2

requirements:
  build:
    - gcc # [osx]
    - gcc 4.8.2 linux_portable # [linux]
    - python
    - numpy
    - jpeg
    - libtiff
    - libpng
    - fftw
    - hdf5
    - boost ==1.55
    - zlib
    - nose
    
  run:
    - libgcc
    - python
    - numpy
    - jpeg
    - libtiff
    - libpng
    - fftw
    - hdf5
    - boost ==1.55
    - zlib
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

