{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: vigra
  version: "1.11.1post1{{toolset.suffix}}"

source:
  git_url: git://github.com/ukoethe/vigra.git
  git_tag: fb427440da8c42f96e14ebb60f7f22bdf0b7b1b2  # master 2017/07/19

build:
  features:
    - {{toolset.short}}

  script_env:
   - LD_LIBRARY_PATH      # [unix]
   - DYLD_LIBRARY_PATH    # [unix]

  number: 1
  detect_binary_files_with_prefix: true
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - python   2.7.10*{{toolset.suffix}}
    - numpy    1.10.1*{{toolset.suffix}}
    - jpeg     1.2.1*{{toolset.suffix}}
    - libtiff  4.0.6*{{toolset.suffix}}
    - libpng   1.5.13*{{toolset.suffix}}
    - fftw     3.3.4*{{toolset.suffix}}
    - hdf5     1.8.12*{{toolset.suffix}}
    - lemon    1.2.4{{toolset.suffix}}
    - boost    1.55.0*{{toolset.suffix}}
    - nose
    # - sphinx
    - zlib     1.2.8*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python   2.7.10*{{toolset.suffix}}
    - numpy    1.10.1*{{toolset.suffix}} # [win]
    - jpeg     1.2.1*{{toolset.suffix}}
    - libtiff  4.0.6*{{toolset.suffix}}
    - libpng   1.5.13*{{toolset.suffix}} # [win]
    - fftw     3.3.4*{{toolset.suffix}}
    - hdf5     1.8.12*{{toolset.suffix}} # [win]
    - lemon    1.2.4{{toolset.suffix}}
    - boost    1.55.0*{{toolset.suffix}}
    - zlib     1.2.8*{{toolset.suffix}}

# test:
  # imports:
    # - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision
