{% import TOOLSET_CONFIG as toolset %}

package:
  name: vigra
  version: "1.10{{toolset.suffix}}"

source:
  git_url: git://github.com/ukoethe/vigra.git
  git_tag: 35e5d4aed380087d75e206348d1648d9ad9cf1e6 # 2015-07-16

build:
  script_env:
   - LD_LIBRARY_PATH      # [unix]
   - DYLD_LIBRARY_PATH    # [unix]

  number: 9
  detect_binary_files_with_prefix: true
  string: 9_35e5d4a

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.9                   # [unix]
    - numpy    1.7.*{{toolset.suffix}} # [win]
    - jpeg     *{{toolset.suffix}}
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - fftw     3.3.*{{toolset.suffix}}
    - hdf5     1.8.14                  # [unix]
    - hdf5     1.8.*{{toolset.suffix}} # [win]
    - boost    1.55.*{{toolset.suffix}}
    - nose
    # - sphinx
#    - zlib     1.2*     # only indirectly used by vigra

  run:
    - {{toolset.run_requirement}}
    # - libgcc   4.8*                  # [unix]
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.9                   # [unix]
    - numpy    1.7.*{{toolset.suffix}} # [win]
    - jpeg     *{{toolset.suffix}}
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - fftw     3.3.*{{toolset.suffix}}
    - hdf5     1.8.14                  # [unix]
    - hdf5     1.8.*{{toolset.suffix}} # [win]
    - boost    1.55.*{{toolset.suffix}}
#    - zlib     1.2*

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision
