package:
  name: vigra
  version: "1.10"

source:
  git_url: git://github.com/ukoethe/vigra.git
  git_tag: a590b5b5bd313afc5a2fb78adcd609cde28cc993 # 2015-05-05

build:
  script_env:
   - LD_LIBRARY_PATH
   - DYLD_LIBRARY_PATH

  number: 2
  string: a590b5b

requirements:
  build:
    - gcc
    - gcc
    - python
    - numpy
    - jpeg
    - libtiff
    - libpng
    - fftw
    - hdf5
    - boost
    - zlib
    - nose

  run:
    - libgcc
    - python
    - numpy
    - jpeg
    - libtiff
    - libpng
    - fftw
    - hdf5
    - boost
    - zlib
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

