package:
  name: vigra
  version: "1.10"

source:
  git_url: git://github.com/ukoethe/vigra.git
  git_tag: 35e5d4aed380087d75e206348d1648d9ad9cf1e6 # 2015-07-16

build:
  script_env:
   - LD_LIBRARY_PATH      # [unix]
   - DYLD_LIBRARY_PATH    # [unix]

  number: 9
  string: 9_35e5d4a
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99 # [linux]
    - gcc 4.8.2 # [osx]
    - visual-studio 11.0 # [win]
    - python   2.7*
    - numpy    >=1.9     # [unix]
    - numpy    1.7.0.99  # [win]
    - jpeg     8d        # [unix]
    - jpeg     1.2.1.99  # [win]
    - libtiff  4.0*      # [unix]
    - libtiff  4.0.1.99  # [win]
    - libpng   1.6.17    # [unix]
    - libpng   1.5.13    # [win]
    - fftw     3.3*
    - hdf5     1.8.14    # [unix]
    - hdf5     1.8.12    # [win]
    - boost    1.55.0
    - nose
    - sphinx
#    - zlib     1.2*     # only indirectly used by vigra

  run:
    - libgcc   4.8*      # [unix]
    - visual-studio 11.0 # [win]
    - python   2.7*
    - numpy    >=1.9     # [unix]
    - numpy    1.7.0.99  # [win]
    - jpeg     8d        # [unix]
    - jpeg     1.2.1.99  # [win]
    - libtiff  4.0*      # [unix]
    - libtiff  4.0.1.99  # [win]
    - libpng   1.6.17    # [unix]
    - libpng   1.5.13    # [win]
    - fftw     3.3*
    - hdf5     1.8.14    # [unix]
    - hdf5     1.8.12    # [win]
    - boost    1.55.0
    - nose
#    - zlib     1.2*

#test:
#  imports:
#    - vigra   # FIXME: doesn't work on Windows: %LIBRARY_BIN% not in PATH

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

