package:
  name: vigra
  version: "1.11rc"

source:
  git_url: https://github.com/ukoethe/vigra
  git_tag: version-1-11-rc

build:
  number: 0

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{np}}py{{py}}_multicut_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - python 2.7*
    - numpy >=1.9,{{NPY_VER}}*
    - jpeg     8d
    - libtiff  4.0.6
    - libpng   1.6.17
    - fftw     3.3*
    - hdf5     1.8.14
    - h5py
    - boost    1.55.0
    - zlib     1.2*
    - nose

  run:
    - libgcc   4.8*
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - jpeg     8d
    - libtiff  4.0.6   # libtiff version must exactly match from the build (on osx, at least)
    - libpng   1.6.17
    - fftw     3.3*
    - hdf5     1.8.14
    - h5py
    - boost    1.55.0
    - zlib     1.2*
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

