package:
  name: vigra
  version: "1.10"

source:
  git_url: git://github.com/ukoethe/vigra.git
  git_tag: a590b5b5bd313afc5a2fb78adcd609cde28cc993 # 2015-05-05

build:
  script_env:
   - LD_LIBRARY_PATH
   - DYLD_LIBRARY_PATH

  number: 2
  string: a590b5b

requirements:
  build:
    - gcc      4.8.2   5 # [osx]
    - gcc      4.8.2   linux_portable # [linux]
    - python   2.7.9   3
    - numpy    1.9.2   py27_0
    - jpeg     8d      0
    - libtiff  4.0.2   1
    - libpng   1.5.13  1
    - fftw     3.3.4   0
    - hdf5     1.8.14  0
    - boost    1.55.0  1
    - zlib     1.2.8   0
    - nose     1.3.6   py27_0

  run:
    - libgcc   4.8.4   1
    - python   2.7.9   3
    - numpy    1.9.2   py27_0
    - jpeg     8d      0
    - libtiff  4.0.2   1
    - libpng   1.5.13  1
    - fftw     3.3.4   0
    - hdf5     1.8.14  0
    - boost    1.55.0  1
    - zlib     1.2.8   0
    - nose     1.3.6   py27_0

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

