about:
  summary: "A meta-package for building all ilastik dependencies and downloading the ilastik-meta repo."

package:
  name: ilastik-everything-but-tracking
  version: "" # build.sh will generate a __conda_version__.txt file

requirements:
  build:
    - ilastik-deps-pc
    - ilastik-deps-pc-iiboost
    - ilastik-deps-carving >=1.1.6a7
    - ilastik-meta

  run:
    - ilastik-versions
    - ilastik-deps-pc
    - ilastik-deps-pc-iiboost
    - ilastik-deps-carving >=1.1.6a7
    - ilastik-meta

test:
  requires:
    - nose
    
  imports:
    - lazyflow
    - volumina
    - ilastik
