{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all ilastik dependencies and downloading the ilastik-meta repo."

package:
  name: ilastik-everything-but-tracking
  # build scripts will prepend actual version via a __conda_version__.txt file
  version: "{{toolset.suffix}}"

build:
  track_features:
    - {{toolset.short}}
  features:
    - {{toolset.short}}
  number: 2

requirements:
  build:
    - {{toolset.build_requirement}}
    - ilastik-deps-pc          *{{toolset.suffix}}
    - ilastik-deps-pc-iiboost  *{{toolset.suffix}}
    # - ilastik-deps-carving >=1.1.6a7,*{{toolset.suffix}}
    - ilastik-deps-carving     >=1.1.6a7                 # [unix]
    - ilastik-deps-carving     1.1.6a7{{toolset.suffix}} # [win]
    - ilastik-exe              >1.0,*{{toolset.suffix}}  # [win]
    - ilastik-meta
    - ilastik-versions

  run:
    - {{toolset.run_requirement}}
    - ilastik-deps-pc          *{{toolset.suffix}}
    - ilastik-deps-pc-iiboost  *{{toolset.suffix}}
    # - ilastik-deps-carving >=1.1.6a7,*{{toolset.suffix}}
    - ilastik-deps-carving     >=1.1.6a7                 # [unix]
    - ilastik-deps-carving     1.1.6a7{{toolset.suffix}} # [win]
    - ilastik-exe              >1.0,*{{toolset.suffix}}  # [win]
    - ilastik-meta
    - ilastik-versions

test:
  requires:
    - nose

  imports:
    - lazyflow
    - volumina
    - ilastik
