about:
  summary: "A meta-package for building all ilastik dependencies and downloading the ilastik-meta repo."

package:
  name: ilastik-everything-but-tracking
  version: "" # build.sh will generate a __conda_version__.txt file

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  number: 1
  string: 1_{{ vc }}                 # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - ilastik-deps-pc
    - ilastik-deps-pc-iiboost
    - ilastik-deps-carving >=1.1.6a7
    - ilastik-meta

  run:
    - ilastik-deps-pc
    - ilastik-deps-pc-iiboost
    - ilastik-deps-carving >=1.1.6a7
    - ilastik-meta

test:
  requires:
    - nose
    
  imports:
    - lazyflow
    - volumina
    - ilastik
