package:
  name: pip
  version: 7.1.0

source:
  fn:  pip-7.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pip/pip-7.1.0.tar.gz
  md5: d935ee9146074b1d3f26c5f0acfd120e

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: FIXME
  license: FIXME
  summary: FIXME

