package:
  name: neuroproof 
  version: "0.0.1"
  
source:
  git_url: https://github.com/janelia-flyem/lowtis
  git_tag: HEAD

build:
  {% set build_num = 1 %}
  number: {{ build_num }}
  string: {{build_num}}_g{{GIT_FULL_HASH[:7]}} 

  detect_binary_files_with_prefix: true # (defaults to false)

requirements:
  build:
    - gcc 4.8.5
    - libdvid-cpp >=0.2
    
  run:
    - libgcc
    - libdvid-cpp >=0.2

about:
  home: http://github.com/janelia-flyem/lowtis
  license: BSD (3-clause)
  summary: C++ library for low-latency image fetching
