about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-carving
  version: "1.1"

requirements:
  run:
    - ilastik-deps-pc
    - cylemon
