about:
  summary: "A meta-package for building all the dependencies needed for only carving."

package:
  name: ilastik-deps-carving
  version: "1.1"

requirements:
  build:
    - ilastik-deps-pc
    - cylemon

  run:
    - ilastik-deps-pc
    - cylemon
