{% import TOOLSET_CONFIG as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for only carving."

package:
  name: ilastik-deps-carving
  version: "1.1.6a7{{toolset.suffix}}"

requirements:
  build:
    - ilastik-deps-pc   *{{toolset.suffix}}
    - ilastiktools      *{{toolset.suffix}}

  run:
    - ilastik-deps-pc   *{{toolset.suffix}}
    - ilastiktools      *{{toolset.suffix}}
