about:
  summary: "A meta-package for building all the dependencies needed for only carving."

package:
  name: ilastik-deps-carving
  version: "1.1.6a7"

requirements:
  build:
    - ilastik-deps-pc
    - ilastiktools

  run:
    - ilastik-deps-pc
    - ilastiktools
