about:
  summary: "A meta-package for building all the dependencies needed for only carving."

package:
  name: ilastik-deps-carving
  version: "1.1"

requirements:
  build:
    - ilastik-deps-pc 1.1 0
    - cylemon 1 np19py27_0

  run:
    - ilastik-deps-pc 1.1 0
    - cylemon 1 np19py27_0
