{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for only carving."

package:
  name: ilastik-deps-carving
  version: "1.2.0{{toolset.suffix}}"

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - ilastik-deps-pc   *{{toolset.suffix}}
    - ilastiktools      *{{toolset.suffix}}

  run:
    - ilastik-deps-pc   *{{toolset.suffix}}
    - ilastiktools      *{{toolset.suffix}}
