{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: emulate_c99
  version: "1.0{{toolset.suffix}}"
  
build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}

  # emulate_c99 is static library, has no runtime requirements
