{% import TOOLSET_CONFIG as toolset %}

package:
  name: emulate_c99
  version: "1.0{{toolset.suffix}}"
  
requirements:
  build:
    - {{toolset.build_requirement}}

  # emulate_c99 is static library, has no runtime requirements
