package:
  # pure python
  name: pyqtgraph
  version: "0.9.10"

source:
  git_url: https://github.com/pyqtgraph/pyqtgraph.git
  git_tag: pyqtgraph-0.9.10

requirements:
  build:
    - python
    - numpy
    - pyqt
    - pyopengl

  run:
    - python
    - numpy
    - pyqt
    - pyopengl

test:
  imports:
      - pyqtgraph

about:
  home: http://www.pyqtgraph.org/
  license: MIT
  summary: Scientific Graphics and GUI Library
