{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: pyqt
  version: "4.11.3{{toolset.suffix}}"

source:

  fn:  PyQt-mac-gpl-4.11.3.tar.gz                                                                # [osx]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-mac-gpl-4.11.3.tar.gz   # [osx]
  sha1: 8c53254b38686e5366d74eba81f02f9611f39166                                                 # [osx]

  fn:  PyQt-x11-gpl-4.11.3.tar.gz                                                                # [linux]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz   # [linux]
  sha1: 28259b175c0befed328087702e8b93b819c99895                                                 # [linux]

  fn:  PyQt-win-gpl-4.11.3.zip                                                                   # [win]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-win-gpl-4.11.3.zip      # [win]
  md5: 53321bb872e665b3e89904df92a2e9ea                                                          # [win]

  patches:              # [unix]
    - configure.patch   # [unix]

build:
  features:
    - {{toolset.short}}
  number: 6
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - qt          4.8.6.99                # [unix]
    - qt-with-src 4.8.*{{toolset.suffix}} # [win]
    - qt          4.8.*{{toolset.suffix}} # [win] (needed here to initiate recursive creation)
    # note: sip >=4.16 is incompatible with PyQt 4.10.3
    # note: sip <4.16  is incompatible with PyQt 4.11.3
    # - sip     >=4.16.4,*{{toolset.suffix}}
    - sip     >=4.16.4                    # [unix]
    - sip     4.16.9{{toolset.suffix}}    # [win]
    
  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - qt     4.8.6.99                    # [unix]
    - qt     4.8.*{{toolset.suffix}}     # [win]
    # - sip     >=4.16.4,*{{toolset.suffix}}
    - sip     >=4.16.4                   # [unix]
    - sip     4.16.9{{toolset.suffix}}   # [win]

test: 
  imports:
    - PyQt4

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL

