package:
    name: opengm
    version: "2.3.4"

source:
    git_url: https://github.com/opengm/opengm.git
    git_tag: 0e55e0ba9db734c58349024e898121e2f9315c06

build:
  number: 6
  string: 6_g0e55e0ba9
  detect_binary_files_with_prefix: true

requirements:
    build:
      - gcc 4.8.5 # [linux]
      - gcc 4.8.5 # [osx]
      - boost 1.55.0
      - python
      - numpy
      - hdf5 1.8.14
    run:
      - libgcc
      - boost 1.55.0
      - python
      - numpy
      - hdf5 1.8.14

test:
  imports:
    - opengm
# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
    summary: 'A C++ Library for Discrete Graphical Models'
