package:
    name: opengm
    version: "2.3.4"

source:
    git_url: https://github.com/opengm/opengm.git
    git_tag: HEAD

requirements:
    build:
      - gcc     4.8.2   5 # [osx]
      - gcc     4.8.2   linux_portable # [linux]
      - boost   1.55.0  1
      - python  2.7.9   3
      - numpy   1.9.2   py27_0
      - hdf5    1.8.14  0
    run:
      - libgcc  4.8.4   1
      - boost   1.55.0  1
      - python  2.7.9   3
      - numpy   1.9.2   py27_0
      - hdf5    1.8.14  0

test:
  imports:
    - opengm
# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
    summary: 'A C++ Library for Discrete Graphical Models'
