{% if not WITH_CPLEX is defined %}
  {% set WITH_CPLEX = false %}
{% endif %}

package:
  {% if WITH_CPLEX %}
    name: opengm-with-cplex
  {% else %}
    name: opengm
  {% endif %}

    version: "2.3.7.post29"

source:
  #git_url: https://github.com/opengm/opengm
  git_url: https://github.com/DerThorsten/opengm
  git_rev: a00f9958e8dc79d51f22b9c00e3093bd8bd32ae0

  patches:
    - patches/patchConicBundle.patch # Yes, we're patching the patch script (ignore ssl certificate problems)
    - patches/patchDAOOPT.sh.patch # Apparently old versions of wget don't choose the same default filename for github zip files.
    - patches/patchPlanarity.sh.patch # Apparently the mirror at http://jgaa.info is not reliable, but the parent website is.

build:
  number: 3

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{CONDA_NPY[:]}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  detect_binary_files_with_prefix: true
  script_env:
     - WITH_CPLEX
     - WITH_EXTERNAL_LIBS
     - CPLEX_ROOT_DIR

requirements:
  build:
    - gcc 4.8.5 # [unix]
    - boost 1.55.0
    - python 2.7*
    - numpy >=1.9,{{NPY_VER}}*
    - hdf5 1.8.16
    - vigra >=1.11
    
    {% if WITH_CPLEX %}
    - cplex-shared # Need to make sure that cplex dylibs exist
    {% endif %}

  run:
    - libgcc # [unix]
    - boost 1.55.0
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - hdf5 1.8.16

    {% if WITH_CPLEX %}
    - cplex-shared # Need to make sure that cplex dylibs exist and are linked into the environment
    {% endif %}
    
    # At build time, vigra is needed on the C++ side for header-only stuff,
    # but isn't needed at runtime (e.g. for python stuff) 
    # - vigra >=1.11

test:
  {% if WITH_CPLEX %}
    imports:
      - opengm_with_cplex
  {% else %}
    imports:
      - opengm
  {% endif %}

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
  {% if WITH_CPLEX %}
    summary: 'A C++ Library for Discrete Graphical Models. This package was linked against the CPLEX commercial ILP solver, which you will need to install separately.'
  {% else %}
    summary: 'A C++ Library for Discrete Graphical Models'
  {% endif %}

    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
