package:
    name: opengm
    version: "2.3.6.post1"

source:
    #git_url: https://github.com/opengm/opengm
    #git_tag: 3f68450da8b3c7ef11e2614c4a0acf5866851115 # 2015-12-10
    git_url: https://github.com/stuarteberg/opengm
    git_tag: fix-apple

build:
  {% set build_num = 9 %}
  number: {{ build_num }}

  {% if WITH_CPLEX %}
      {% set cplex_string = '_with_cplex' %}
  {% else %}
      {% set cplex_string = '' %}
  {% endif %}

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{CONDA_NPY[:]}}py{{CONDA_PY}}_{{build_num}}_g{{GIT_FULL_HASH[:7]}}{{cplex_string}}

  detect_binary_files_with_prefix: true
  script_env:
     - WITH_CPLEX
     - CPLEX_ROOT_DIR

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - boost 1.55.0
    - python 2.7*
    - numpy >=1.9,{{NPY_VER}}*
    - hdf5 1.8.14
  run:
    - libgcc
    - boost 1.55.0
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - hdf5 1.8.14

test:
  imports:
    - opengm

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
    summary: 'A C++ Library for Discrete Graphical Models'
