{% import TOOLSET_CONFIG as toolset %}

package:
    name: opengm
    version: "2.3.4{{toolset.suffix}}"

source:
    git_url: https://github.com/opengm/opengm.git
    #git_tag: 376d06198aba59e6e37da520b9f34713f6d05674
    # FIXME: Python bindings of commit 89d44d0 don't compile on Windows
    git_tag: 89d44d01920863f0b8df4a235b00e15adbd2b583 # intentionally downgraded relative to the previous build.

build:

build:
  number: 5
  string: 5_g89d44d0                 # Downgraded relative to build 4
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - boost 1.55.*{{toolset.suffix}}
    - python  2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - hdf5     1.8.14                  # [unix]
    - hdf5     1.8.*{{toolset.suffix}} # [win]
  run:
    - {{toolset.run_requirement}}
    # - libgcc                         # [unix]
    - boost 1.55.*{{toolset.suffix}}
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - hdf5     1.8.14                  # [unix]
    - hdf5     1.8.*{{toolset.suffix}} # [win]

# FIXME: upgrade opengm to make the Python bindings work on Windows 
test:          # [unix]
  imports:     # [unix]
    - opengm   # [unix]

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
    summary: 'A C++ Library for Discrete Graphical Models'
