{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: theano
  version: "0.7{{toolset.suffix}}"

source:
  git_url: https://github.com/Theano/Theano.git
  git_tag: rel-0.7

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - python    *{{toolset.suffix}}
    - numpy     >=1.10,*{{toolset.suffix}}
    - scipy     *{{toolset.suffix}}
    - setuptools

  run:
    - {{toolset.run_requirement}}
    - python    *{{toolset.suffix}}
    - numpy     >=1.10,*{{toolset.suffix}}
    - scipy     *{{toolset.suffix}}

about:
  home: http://deeplearning.net/software/theano/
  license: BSD License
  summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.