package:
  # pure python
  name: requests
  version: "2.8.1"

source:
  git_url: https://github.com/kennethreitz/requests.git
  git_tag: v2.8.1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
      - requests

about:
  home: http://python-requests.org/
  license: Apache2
  summary: HTTP Requests for Humans
