{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

package:
  name: visual-studio
  version: {{ vc_version }} # [win]

build:
  track_features:
    - {{ vc }}        # [win]
  features:
    - {{ vc }}        # [win]
