{% import TOOLSET_CONFIG as toolset %}

package:
  name: scikit-image
  version: "0.11.3{{toolset.suffix}}"

source:
  fn:  scikit-image-0.11.3.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-image/scikit-image-0.11.3.tar.gz
  md5: 5cd60fe78adbe30254a87081f12500f9

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}
    - scipy  *{{toolset.suffix}}
    - cython                          # [unix]
    - cython  0.23{{toolset.suffix}}  # [win]
    - pillow  *{{toolset.suffix}}
    - networkx
    - six
    - matplotlib 1.4.*{{toolset.suffix}} # [win]
    - decorator
    - pyparsing
    - pytz
    - python-dateutil

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}
    - scipy  *{{toolset.suffix}}
    - cython                          # [unix]
    - cython  0.23{{toolset.suffix}}  # [win]
    - pillow  *{{toolset.suffix}}
    - networkx
    - six
    - matplotlib 1.4.*{{toolset.suffix}} # [win]
    - decorator
    - pyparsing
    - pytz
    - python-dateutil

about:
  home: http://scikit-image.org/
  license: BSD
  summary: image processing
