package:
  name: scikit-image
  version: 0.11.3

source:
  fn:  scikit-image-0.11.3.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-image/scikit-image-0.11.3.tar.gz
  md5: 5cd60fe78adbe30254a87081f12500f9

requirements:
  build:
    - visual-studio 11.0   # [win]
    - python 2.7.10        # [win]
    - numpy 1.7.0.99       # [win]
    - scipy
    - cython
    - pillow
    - networkx
    - six
    - matplotlib 1.4.3.99  # [win]
    - decorator
    - pyparsing
    - pytz
    - python-dateutil

  run:
    - visual-studio 11.0   # [win]
    - python 2.7.10        # [win]
    - numpy 1.7.0.99       # [win]
    - scipy
    - cython
    - pillow
    - networkx
    - six
    - matplotlib 1.4.3.99  # [win]
    - decorator
    - pyparsing
    - pytz
    - python-dateutil

about:
  home: http://scikit-image.org/
  license: BSD
  summary: image processing

