{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for creating installers."

package:
  name: ilastik-package
  version: "1.0"

requirements:
  run:
    - ilastik-everything   *{{toolset.suffix}}
