package:
  name: setuptools
  version: 18.2

source:
  fn:  setuptools-18.2.tar.gz
  url: https://pypi.python.org/packages/source/s/setuptools/setuptools-18.2.tar.gz
  md5: 52b4e48939ef311d7204f8fe940764f4

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: https://pypi.python.org/pypi/setuptools
  license: PSF
  summary: Easily download, build, install, upgrade, and uninstall Python packages

