{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: libtiff
  version: "4.0.6{{toolset.suffix}}"

source:
    fn:  tiff-4.0.6.tar.gz
    md5: d1d2e940dea0b5ad435f21f03d96dd72
    url: http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz

build:
  features:
    - {{toolset.short}}
  number: 2
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - zlib  *{{toolset.suffix}}
    - jpeg  *{{toolset.suffix}}
    - xz

  run:
    - {{toolset.run_requirement}}
    - zlib  *{{toolset.suffix}}
    - jpeg  *{{toolset.suffix}}
    - xz

about:
  home: http://www.libtiff.org
  license: MIT
  summary: TIFF image format I/O
