package:
  name: libtiff
  version: "4.0.1.99"

source:
    fn:  tiff-4.0.1.tar.gz
    md5: fae149cc9da35c598d8be897826dfc63
    url: http://download.osgeo.org/libtiff/tiff-4.0.1.tar.gz

requirements:
  build:
    - visual-studio 11.0 # [win]
    - zlib
    - jpeg  1.2.1.99     # [win]

  run:
    - visual-studio 11.0 # [win]
    - zlib
    - jpeg  1.2.1.99     # [win]

about:
  home: http://www.libtiff.org
  license: MIT
  summary: TIFF image format I/O
