package:
  name: h5py
  version: "2.5.0"

source:
  fn:  h5py-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/h/h5py/h5py-2.5.0.tar.gz
  md5: 6e4301b5ad5da0d51b0a1e5ac19e3b74

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - python
    - hdf5
    - numpy
    - cython
    - six
    - pkgconfig
    - nose

  run:
    - python
    - hdf5
    - numpy
    - cython
    - six

about:
  home: http://www.h5py.org
  license: BSD
  summary: Read and write HDF5 files from Python
