{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: h5py
  version: "2.5.0{{toolset.suffix}}"

source:
  fn:  h5py-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/h/h5py/h5py-2.5.0.tar.gz
  md5: 6e4301b5ad5da0d51b0a1e5ac19e3b74

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - python    *{{toolset.suffix}}
    - hdf5      *{{toolset.suffix}}
    - numpy     *{{toolset.suffix}}
    - cython    *{{toolset.suffix}}
    - six
    - pkgconfig
    - nose

  run:
    - python    *{{toolset.suffix}}
    - hdf5      *{{toolset.suffix}}
    - numpy     *{{toolset.suffix}}
    - cython    *{{toolset.suffix}}
    - six

about:
  home: http://www.h5py.org
  license: BSD
  summary: Read and write HDF5 files from Python
