{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: h5py
  version: "2.5.0post1{{toolset.suffix}}"  # post1 since numpy was upgraded

source:
  git_url: https://github.com/h5py/h5py.git
  git_tag: 2.5.0

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - python    *{{toolset.suffix}}
    - hdf5      *{{toolset.suffix}}
    - numpy     >=1.10,*{{toolset.suffix}}
    - cython    *{{toolset.suffix}}
    - six
    - pkgconfig
    - nose

  run:
    - python    *{{toolset.suffix}}
    - hdf5      *{{toolset.suffix}}
    - numpy     >=1.10,*{{toolset.suffix}}
    - cython    *{{toolset.suffix}}
    - six

about:
  home: http://www.h5py.org
  license: BSD
  summary: Read and write HDF5 files from Python
