about:
  summary: "A meta-package for building all the dependencies needed for pixel classification using IIBoost synapse detection."

package:
  name: ilastik-deps-pc-iiboost
  version: "1.1"

build:
  number: 1

requirements:
  run:
    - ilastik-deps-pc
    - iiboost
