about:
  summary: "A meta-package for building all the dependencies needed for pixel classification using IIBoost synapse detection."

package:
  name: ilastik-deps-pc-iiboost
  version: "1.1"

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - ilastik-deps-pc
    - iiboost

  run:
    - ilastik-deps-pc
    - iiboost
