{% import 'CONDA_ENVIRONMENT/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for pixel classification using IIBoost synapse detection."

package:
  name: ilastik-deps-pc-iiboost
  version: "1.1{{toolset.suffix}}"

requirements:
  build:
    - ilastik-deps-pc  *{{toolset.suffix}}
    - iiboost          *{{toolset.suffix}}

  run:
    - ilastik-deps-pc  *{{toolset.suffix}}
    - iiboost          *{{toolset.suffix}}
