package:
  name: lemon
  version: "1.2.4"

source:
  fn: lemon-1.2.4.tar.gz
  url: http://lemon.cs.elte.hu/pub/sources/lemon-1.2.4.tar.gz
  md5: fd89e8bf5035b02e2622a48ac7fe0641

  patches:                # [not win]
    - lemon.patch         # [not win]
    - lemon-test.patch    # [not win]

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99       # [linux]
    - gcc 4.8.2          # [osx]
    - visual-studio 11.0 # [win]
    - python  2.7.10     # [win]

  run:
    - libgcc             # [not win]
    - visual-studio 11.0 # [win]
    - python  2.7.10     # [win]

about:
  home: http://lemon.cs.elte.hu/trac/lemon
  license: Boost
  summary: Library for Efficient Modeling and Optimization in Networks
