package:
  name: lemon
  version: "1.2.4"

source:
  fn: lemon-1.2.4.tar.gz
  url: http://lemon.cs.elte.hu/pub/sources/lemon-1.2.4.tar.gz
  md5: fd89e8bf5035b02e2622a48ac7fe0641

  patches:                # [unix]
    - lemon.patch         # [unix]
    - lemon-test.patch    # [unix]

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  number: 1
  detect_binary_files_with_prefix: true
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - gcc 4.8.2.99                   # [linux]
    - gcc 4.8.2                      # [osx]
    - python  2.7.*

  run:
    - libgcc                         # [unix]
    - visual-studio {{ vc_version }} # [win]
    - python  2.7.*

about:
  home: http://lemon.cs.elte.hu/trac/lemon
  license: Boost
  summary: Library for Efficient Modeling and Optimization in Networks

