{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: lemon
  version: "1.2.4{{toolset.suffix}}"

source:
  fn: lemon-1.2.4.tar.gz
  url: http://lemon.cs.elte.hu/pub/sources/lemon-1.2.4.tar.gz
  md5: fd89e8bf5035b02e2622a48ac7fe0641

  patches:                # [unix]
    - lemon.patch         # [unix]
    - lemon-test.patch    # [unix]

build:
  features:
    - {{toolset.short}}
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python  2.7.*{{toolset.suffix}}

  run:
    # - libgcc                         # [unix]
    - {{toolset.run_requirement}}
    - python  2.7.*{{toolset.suffix}}

about:
  home: http://lemon.cs.elte.hu/trac/lemon
  license: Boost
  summary: Library for Efficient Modeling and Optimization in Networks

