package:
    name: wsdt
    version: 0.2.post4

source:
  git_url: https://github.com/ilastik/wsdt
  git_tag: 5ed2c213aeef270a7bff59810b7a957b19d004cf # master 2016/10/27

build:
  number: 0
  string: py27_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - python 2.7*
    - setuptools

  run:
    - python 2.7*
    - numpy
    - vigra >=1.11
    - networkx

about:
  summary: Implementation of a distance-transform-based watershed algorithm
