package:
  name: dvid
  version: "0.8.7"

source:
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.7/dvid-mac-v0.8.7.tar.gz # [osx]
  md5: bcdc4ba5f6c886a56bcd09e3a49119c7 # [osx]
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.7/dvid-linux-v0.8.7.tar.gz # [linux]
  md5: 578009f6242342928d3d7b6f341457b0 # [linux]

build:
  number: 0

requirements:
  build:

  run:

about:
  home: http://github.com/janelia-flyem/dvid
  license: GPL
