{% import TOOLSET_CONFIG as toolset %}

package:
  name: ilastiktools
  version: "0.1{{toolset.suffix}}"

source:
  git_url: git://github.com/ilastik/ilastiktools.git
  git_tag: afd850125a40e027e78eae1a78e03c20a961ea6a
  git_tag: 

build:
  number: 1
  detect_binary_files_with_prefix: true
  string: afd8501

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - vigra    *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    # - libgcc             # [unix]
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - vigra    *{{toolset.suffix}}

test:
  imports:
    - ilastiktools

about:
  home: http://ilastik.org
  license: GPLv3
  summary: Various compiled utilities for the ilastik project

