{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: ilastiktools
  version: "0.1post3{{toolset.suffix}}"

source:
  git_url: git://github.com/ilastik/ilastiktools.git
  git_tag: f68665df6406856d00ef9ae5af64278d685df564 # master 2016/07/07

build:
  features:
    - {{toolset.short}}
  number: 0
  detect_binary_files_with_prefix: true
  string: 0_gf68665d
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.10,*{{toolset.suffix}}
    - vigra    1.10*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    # - libgcc             # [unix]
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.10,*{{toolset.suffix}}
    - vigra    1.10*{{toolset.suffix}}

about:
  home: http://ilastik.org
  license: GPLv3
  summary: Various compiled utilities for the ilastik project

