{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: ilastiktools
  version: "0.2post1{{toolset.suffix}}"

source:
  git_url: git://github.com/ilastik/ilastiktools.git
  git_tag: 731565e0be509e3a847b3a7d277aacee1ee0161a # master 2016/08/16

build:
  features:
    - {{toolset.short}}
  number: 1
  detect_binary_files_with_prefix: true
  string: 1_g731565e
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.10,*{{toolset.suffix}}
    - vigra    1.11*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    # - libgcc             # [unix]
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.10,*{{toolset.suffix}}
    - vigra    1.11*{{toolset.suffix}}

about:
  home: http://ilastik.org
  license: GPLv3
  summary: Various compiled utilities for the ilastik project
