package:
  name: ilastiktools
  version: "0.1"

source:
  git_url: git://github.com/ilastik/ilastiktools.git
  git_tag: afd850125a40e027e78eae1a78e03c20a961ea6a
  git_tag: 

build:

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  number: 1
  detect_binary_files_with_prefix: true
  string: afd8501                    # [unix]
  string: afd8501_{{ vc }}           # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - gcc 4.8.2.99                   # [linux]
    - gcc 4.8.2                      # [osx]
    - python   2.7.*
    - numpy                          # [unix]
    - numpy    1.7.0                 # [win]
    - vigra

  run:
    - visual-studio {{ vc_version }} # [win]
    - libgcc             # [unix]
    - python   2.7.*
    - numpy                          # [unix]
    - numpy    1.7.0                 # [win]
    - vigra

test:
  imports:
    - ilastiktools

about:
  home: http://ilastik.org
  license: GPLv3
  summary: Various compiled utilities for the ilastik project

