package:
    name: pgmlink
    version: "1.2"

source:
    git_url: https://github.com/stuarteberg/pgmlink
    git_tag: HEAD

requirements:
    build:
      - gcc
      - cplex-shared

    run:
      - libgcc
      - patchelf
      - ann
      - boost
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2

      # We don't require cplex-shared here because it only needs to be installed once per machine,
      # and requiring it here would include all of gcc in the install lib dir.
      # Instead, we give the user a descriptive error message if cplex-shared hasn't been run on her machine.
      # - cplex-shared

build:
  script_env:
     - CPLEX_ROOT_DIR
  number: 4

test:
  imports:
      - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
