{% import TOOLSET_CONFIG as toolset %}

package:
    name: pgmlink
    version: "1.2{{toolset.suffix}}"

source:
    #git_url: https://github.com/martinsch/pgmlink
    #git_tag: ce86cf509b60aaceb4e4bcf392698c2fc6e7e1fd

    git_url: https://github.com/martinsch/pgmlink
    git_tag: 7a0c8d4f54e9a4066991829fb52b411a02914666 # Version from ilastik 1.1.5, downgrade relative to above commit

build:
  number: 11
  string: 11_g7a0c8d4
  script_env:
     - CPLEX_ROOT_DIR
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - cplex-shared                        # [unix]
    - patchelf                            # [linux]
    - ann     *{{toolset.suffix}}
    - boost 1.55.*{{toolset.suffix}}
    - vigra   *{{toolset.suffix}}
    - opengm  *{{toolset.suffix}}
    - mlpack  *{{toolset.suffix}}
    - lemon   *{{toolset.suffix}}
    - libxml2 *{{toolset.suffix}}
    - dlib                                # [unix]
    - armadillo 4.000.2                   # [unix]
    - armadillo 4.320.*{{toolset.suffix}} # [win]

  run:
    - {{toolset.run_requirement}}
    # - libgcc                            # [unix]
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - patchelf                            # [linux]
    - ann     *{{toolset.suffix}}
    - boost 1.55.*{{toolset.suffix}}
    - vigra   *{{toolset.suffix}}
    - opengm  *{{toolset.suffix}}
    - mlpack  *{{toolset.suffix}}
    - lemon   *{{toolset.suffix}}
    - libxml2 *{{toolset.suffix}}
    - dlib                                # [unix]
    - armadillo 4.000.2                   # [unix]
    - armadillo 4.320.*{{toolset.suffix}} # [win]

    # We don't require cplex-shared here because it only needs to be installed once per machine,
    # and requiring it here would include all of gcc in the install lib dir.
    # Instead, we give the user a descriptive error message if cplex-shared hasn't been run on her machine.
    # - cplex-shared

test:
  imports:
    - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'

