package:
    name: pgmlink
    version: "1.2"

source:
    git_url: https://github.com/martinsch/pgmlink
    git_tag: c944c6764a85b88e94ff12c38baa1a8172d9be72 

build:
  number: 14            # [linux]
  string: 14_gc944c67   # [linux]
  number: 17            # [osx]
  string: 17_gc944c67   # [osx]

  detect_binary_files_with_prefix: true
  script_env:
     - CPLEX_ROOT_DIR

requirements:
    build:
      - gcc 4.8.5 # [linux]
      - gcc 4.8.5 # [osx]
      - cplex-shared
      - patchelf # [linux]
      - ann
      - boost 1.55.0
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2
      - dlib
      - armadillo 4.000.2

    run:
      - libgcc
      - patchelf # [linux]
      - ann
      - boost 1.55.0
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2
      - dlib

      # We don't require cplex-shared here because it only needs to be installed once per machine,
      # and requiring it here would include all of gcc in the install lib dir.
      # Instead, we give the user a descriptive error message if cplex-shared hasn't been run on her machine.
      # - cplex-shared

test:
  imports:
      - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
