package:
    name: pgmlink
    version: "1.2"

source:
    git_url: https://github.com/stuarteberg/pgmlink
    git_tag: HEAD

requirements:
    build:
      - gcc # [osx]
      - gcc 4.8.2 linux_portable # [linux]
      - cplex-shared
      - ann
      - boost ==1.55
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2

    run:
      - libgcc
      - cplex-shared # Note: This pulls in gcc as a runtime dependency!
      - ann
      - boost ==1.55
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2
      - patchelf # [linux]

build:
  script_env:
     - CPLEX_ROOT_DIR
  number: 3

test:
  imports:
      - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
