{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
    name: pgmlink-with-cplex
    version: "1.3.post4{{toolset.suffix}}"

source:
    git_url: https://github.com/ilastik/pgmlink
    git_tag: cf4d3da9c72312a3c2076b7af4b95d8e8344b1f2 # master 2016/09/19

build:
  features:
    - {{toolset.short}}
  number: 1
  string: {{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  script_env:
     - CPLEX_ROOT_DIR
  detect_binary_files_with_prefix: true
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - cplex-shared                        # [unix]
    - patchelf                            # [linux]
    - ann     *{{toolset.suffix}}
    - boost 1.55.*{{toolset.suffix}}
    - vigra    1.11.*{{toolset.suffix}}
    # note: pgmlink needs the header files of the experimental-learning
    # branch of opengm. Since opengm-with-cplex is now built from the
    # same branch, we don't need an extra package here.
    - opengm-with-cplex  2.3.7post29{{toolset.suffix}}
    - mlpack  *{{toolset.suffix}}
    - lemon   *{{toolset.suffix}}
    - libxml2 *{{toolset.suffix}}
    - dlib    *{{toolset.suffix}}
    - armadillo 4.000.2                   # [unix]
    - armadillo 6.500.*{{toolset.suffix}} # [win]

  run:
    - {{toolset.run_requirement}}
    # - libgcc                            # [unix]
    - python  2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - patchelf                            # [linux]
    - ann     *{{toolset.suffix}}
    - boost 1.55.*{{toolset.suffix}}
    - vigra   1.11.*{{toolset.suffix}}
    - mlpack  *{{toolset.suffix}}
    - lemon   *{{toolset.suffix}}
    - libxml2 *{{toolset.suffix}}
    - dlib    *{{toolset.suffix}}
    - armadillo 4.000.2                   # [unix]
    - armadillo 6.500.*{{toolset.suffix}} # [win]

    # We don't require cplex-shared here because it only needs to be installed once per machine,
    # and requiring it here would include all of gcc in the install lib dir.
    # Instead, we give the user a descriptive error message if cplex-shared hasn't been run on her machine.
    # - cplex-shared

# test:
  # imports:
    # - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'

