package:
    name: pgmlink
    version: "1.2"

source:
    git_url: https://github.com/martinsch/pgmlink
    git_tag: HEAD

requirements:
    build:
      - ann
      - boost
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2
    run:
      - ann
      - boost
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2

build:
  number: 1 

test:
  imports:
      - pgmlink

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
