package:
    name: pgmlink
    version: "1.3"

source:
    git_url: https://github.com/ilastik/pgmlink
    git_tag: HEAD 

build:
  number: 1

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{np}}py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  detect_binary_files_with_prefix: true
  script_env:
     - CPLEX_ROOT_DIR

requirements:
  build:
    - libgcc
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - cplex-shared
    - patchelf # [linux]
    - ann
    - boost 1.55.0
    - python {{PY_VER}}*
    - numpy >=1.9,{{NPY_VER}}*
    - vigra 1.11*
    - opengm-structured-learning-headers
    - mlpack
    - lemon
    - libxml2
    - dlib
    - libpng
    - armadillo 6.500.5
    - openblas # [linux]

  run:
    - libgcc
    - patchelf # [linux]
    - ann
    - boost 1.55.0
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - vigra 1.11*
    - mlpack
    - lemon
    - libpng
    - libxml2
    - dlib
    - armadillo 6.500.5
    - openblas # [linux]

    # We don't require cplex-shared here because it only needs to be installed once per machine,
    # and requiring it here would include all of gcc in the install lib dir.
    # Instead, we give the user a descriptive error message if cplex-shared hasn't been run on her machine.
    # - cplex-shared

test:
  imports:
    - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
