package:
    name: pgmlink
    version: "1.2"

source:
    git_url: https://github.com/martinsch/pgmlink
    git_tag: HEAD

requirements:
    build:
      - ann
      - boost
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2
    run:
      - ann
      - boost
      - python
      - numpy
      - vigra
      - opengm
      - mlpack
      - lemon
      - libxml2
      - patchelf # [linux]

build:
  script_env:
     - CPLEX_ROOT_DIR
  number: 3

  # Don't let conda configure the RPATH.
  # We set the rpath ourselves in post-link.sh, so pgmlink can locate CPLEX.
  binary_relocation: false

test:
  imports:
      - pgmlink

about:
    home: https://github.com/martinsch/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
