{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: protobuf
  version: "3.0.0a4{{toolset.suffix}}"

source:
  git_url: https://github.com/google/protobuf.git
  git_tag: 12fb61b292d7ec4cb14b0d60e58ed5c35adda3b7

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - mingw-for-msvc-build           # [win]
    - zlib      *{{toolset.suffix}}
    - python    *{{toolset.suffix}}
    - setuptools
    - six
    # - gmock   # for testing

  run:
    - {{toolset.run_requirement}}
    - zlib      *{{toolset.suffix}}
    - python    *{{toolset.suffix}}
    - six

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD
  summary: Protocol Buffers - Google's data interchange format
