{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: libxml2
  version: "2.9.1{{toolset.suffix}}"

source:
  fn:  libxml2-2.9.1.tar.gz
  url: ftp://xmlsoft.org/libxml2/libxml2-2.9.1.tar.gz
  md5: 9c0cfef285d5c4a5c80d00904ddab380

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - iconv   *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - iconv    *{{toolset.suffix}}

about:
  home: http://www.xmlsoft.org/
  license: MIT
  summary: XML C parser and toolkit


