package:
  name: jpeg
  version: "1.2.1"

source:
    fn:  libjpeg-turbo-1.2.1.tar.gz
    md5: f61e60ff01381ece4d2fe65eeb52669e
    url: http://sourceforge.net/projects/libjpeg-turbo/files/1.2.1/libjpeg-turbo-1.2.1.tar.gz

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - nasm                           # [win]

  run:
    - visual-studio {{ vc_version }} # [win]

about:
  home: http://libjpeg-turbo.virtualgl.org
  license: BSD
  summary: JPEG image format I/O
