{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: jpeg
  version: "1.2.1{{toolset.suffix}}"

source:
    fn:  libjpeg-turbo-1.2.1.tar.gz
    md5: f61e60ff01381ece4d2fe65eeb52669e
    url: http://sourceforge.net/projects/libjpeg-turbo/files/1.2.1/libjpeg-turbo-1.2.1.tar.gz

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - nasm                           # [win]

  run:
    - {{toolset.run_requirement}}

about:
  home: http://libjpeg-turbo.virtualgl.org
  license: BSD
  summary: JPEG image format I/O
