package:
  name: openssl-src-for-python
  version: "1.0.2a"

source:
  git_url: https://github.com/openssl/openssl
  git_tag: OpenSSL_1_0_2a

about:
  home: https://www.openssl.org/
  license: OpenSSL License (BSD style)
  summary:  Cryptography and SSL/TLS Toolkit

