package:
  name: jupyter_core
  version: 4.0.4

source:
  fn:  jupyter_core-4.0.4.tar.gz
  url: https://pypi.python.org/packages/source/j/jupyter_core/jupyter_core-4.0.4.tar.gz
  md5: 1d24d79414b8ec18216bf490e101313a

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: https://pypi.python.org/pypi/jupyter_core
  license: BSD
  summary: Jupyter core package

