package:
  # pure python
  name: futures
  version: "2.1.3"

source:
  fn:  futures-2.1.3.tar.gz
  url: https://pypi.python.org/packages/source/f/futures/futures-2.1.3.tar.gz
  md5: 3de68835c8035dff0495cbe7f5c75beb

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://pypi.python.org/pypi/futures
  license: BSD
  summary: high-level interface for asynchronously executing callables
