{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: faulthandler
  version: "2.4{{toolset.suffix}}"

source:
  fn:  faulthandler-2.4.tar.gz
  url: https://pypi.python.org/packages/source/f/faulthandler/faulthandler-2.4.tar.gz
  md5: 110960933b0902334e8804eb4ea20750

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}

about:
  home: https://pypi.python.org/pypi/faulthandler
  license: BSD
  summary: Display the Python traceback on a crash
