package:
  name: faulthandler
  version: 2.4

source:
  fn:  faulthandler-2.4.tar.gz
  url: https://pypi.python.org/packages/source/f/faulthandler/faulthandler-2.4.tar.gz
  md5: 110960933b0902334e8804eb4ea20750

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: https://pypi.python.org/pypi/faulthandler
  license: BSD
  summary: Display the Python traceback on a crash

