{% import 'CONDA_ENVIRONMENT/toolset-info/config.yaml' as toolset %}

package:
  name: openblas
  version: "0.2.5{{toolset.suffix}}"

source:
  git_url: http://github.com/xianyi/OpenBLAS
  git_rev: v0.2.5
  
requirements:
  build:
    - mingw                          # [win]

  run:
    - mingw                          # [win]

about:
  home: www.openblas.ne
  license: BSD
  summary: An optimized BLAS library
