{% import TOOLSET_CONFIG as toolset %}

package:
  name: markupsafe
  version: "0.18{{toolset.suffix}}"

source:
  fn:  MarkupSafe-0.18.tar.gz
  url: https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.18.tar.gz
  md5: f8d252fd05371e51dec2fe9a36890687

requirements:
  build:
    - {{toolset.build_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - setuptools

  run:
    - {{toolset.run_requirement}}
    - python   2.7.*{{toolset.suffix}}

about:
  home: https://pypi.python.org/pypi/MarkupSafe
  license: BSD
  summary: Implements a XML/HTML/XHTML Markup safe string for Python


