package:
  name: markupsafe
  version: 0.18

source:
  fn:  MarkupSafe-0.18.tar.gz
  url: https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.18.tar.gz
  md5: f8d252fd05371e51dec2fe9a36890687

requirements:
  build:
    - python 2.7.10 [win]

  run:
    - python 2.7.10 [win]

about:
  home: https://pypi.python.org/pypi/MarkupSafe
  license: BSD
  summary: Implements a XML/HTML/XHTML Markup safe string for Python

