{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: openblas
  version: "0.2.5{{toolset.suffix}}"

source:
  git_url: http://github.com/xianyi/OpenBLAS
  git_rev: v0.2.5

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - mingw-for-msvc-build           # [win]

  run:
    - mingw-for-msvc                 # [win]

about:
  home: www.openblas.ne
  license: BSD
  summary: An optimized BLAS library
