{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: matplotlib
  version: "1.4.3post1{{toolset.suffix}}"

source:
  fn:  matplotlib-1.4.3.tar.gz
  url: https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.4.3.tar.gz
  md5: 86af2e3e3c61849ac7576a6f5ca44267

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.10,*{{toolset.suffix}}  # [win]
    - libpng   1.5.*{{toolset.suffix}}  # [win]
    - pyqt     4.11.3{{toolset.suffix}} # [win]
    - tornado  *{{toolset.suffix}}      # [win]
    - freetype *{{toolset.suffix}}      # [win]
    - mock
    - nose
    - pyparsing
    - pytz
    - python-dateutil
    - six
    - funcsigs
    - pbr

  run:
    - python   2.7.*{{toolset.suffix}}
    - numpy    >=1.10,*{{toolset.suffix}}  # [win]
    - libpng   1.5.*{{toolset.suffix}}  # [win]
    - pyqt     4.11.3{{toolset.suffix}} # [win]
    - tornado  *{{toolset.suffix}}      # [win]
    - freetype *{{toolset.suffix}}      # [win]
    - mock
    - pyparsing
    - pytz
    - python-dateutil
    - six
    - funcsigs
    - pbr

about:
  home: https://pypi.python.org/pypi/matplotlib
  license: BSD
  summary: Python plotting package
