package:
  name: cylemon
  version: "1"

source:
  git_url: https://github.com/ilastik/cylemon
  git_tag: HEAD

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy
    - lemon

  run:
    - python
    - cython
    - numpy
    - lemon

test:
  # Python imports
  imports:
    - cylemon

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: GPLv3
  summary: 'Very partial cython/python bindings for the lemon graph library '
