package:
  name: cylemon
  version: "1"

source:
  git_url: https://github.com/ilastik/cylemon
  git_tag: HEAD

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.5.99 # [linux]
    - gcc 4.8.5.99 # [osx]
    - python
    - cython 0.21
    - setuptools
    - numpy
    - lemon

  run:
    - libgcc
    - python
    - numpy
    - lemon

test:
  # Python imports
  imports:
    - cylemon

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: GPLv3
  summary: 'Very partial cython/python bindings for the lemon graph library '
