package:
  name: cylemon
  version: "1"

source:
  git_url: https://github.com/ilastik/cylemon
  git_tag: HEAD

requirements:
  build:
    - gcc         4.8.2    5 # [osx]
    - gcc         4.8.2    linux_portable # [linux]
    - python      2.7.9    3
    - cython      0.21     py27_1
    - setuptools  15.2     py27_0
    - numpy       1.9.2    py27_0
    - lemon       1.2.4    0

  run:
    - libgcc      4.8.4    1
    - python      2.7.9    3
    - numpy       1.9.2    py27_0
    - lemon       1.2.4    0

test:
  # Python imports
  imports:
    - cylemon

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: GPLv3
  summary: 'Very partial cython/python bindings for the lemon graph library '
