{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: scikit-learn
  version: "0.16.1post1{{toolset.suffix}}"

source:
  git_url: https://github.com/scikit-learn/scikit-learn.git
  git_tag: 0.16.1

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}
    - scipy  *{{toolset.suffix}}
    - cython                          # [unix]
    - cython  0.23{{toolset.suffix}}  # [win]

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}
    - scipy  *{{toolset.suffix}}
    - cython                          # [unix]
    - cython  0.23{{toolset.suffix}}  # [win]

about:
  home: http://scikit-learn.org
  license: BSD
  summary: Machine Learning in Python
