{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: scikit-learn
  version: "0.16.1{{toolset.suffix}}"

source:
  fn:  scikit-learn-0.16.1.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-learn/scikit-learn-0.16.1.tar.gz
  md5: 363ddda501e3b6b61726aa40b8dbdb7e

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}
    - scipy  *{{toolset.suffix}}
    - cython                          # [unix]
    - cython  0.23{{toolset.suffix}}  # [win]

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}
    - scipy  *{{toolset.suffix}}
    - cython                          # [unix]
    - cython  0.23{{toolset.suffix}}  # [win]

about:
  home: http://scikit-learn.org
  license: BSD
  summary: Machine Learning in Python
