{% import TOOLSET_CONFIG as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-pc
  version: "1.1{{toolset.suffix}}"

build:
  number: 2

requirements:
  build:
    - ilastik-deps-pc-headless   *{{toolset.suffix}}
    - pyqt 4.11.3.99                     # [osx]
    - pyqt 4.11.3{{toolset.suffix}}      # [win or linux]
    - qimage2ndarray *{{toolset.suffix}}
    - vtk  5.10.1.99                     # [unix]
    - vtk  5.10.1{{toolset.suffix}}      # [win]
    - futures
    - matplotlib  *{{toolset.suffix}}

    # Python was already included via the headless package,
    # but we need to add it explicitly here due to a conda bug.
    - python

  run:
    - ilastik-deps-pc-headless
    - pyqt 4.11.3.99                     # [osx]
    - pyqt 4.11.3{{toolset.suffix}}      # [win or linux]
    - qimage2ndarray *{{toolset.suffix}}
    - vtk  5.10.1.99                     # [unix]
    - vtk  5.10.1{{toolset.suffix}}      # [win]
    - futures
    - matplotlib  *{{toolset.suffix}}
