{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-pc
  version: "1.2{{toolset.suffix}}"

build:
  features:
    - {{toolset.short}}
  number: 2

requirements:
  build:
    - {{toolset.build_requirement}}
    - ilastik-deps-pc-headless   *{{toolset.suffix}}
    - pyqt 4.11.3.99                     # [osx]
    - pyqt 4.11.3{{toolset.suffix}}      # [win or linux]
    - qimage2ndarray *{{toolset.suffix}}
    - vtk  5.10.1.99                     # [unix]
    - vtk  5.10.1{{toolset.suffix}}      # [win]
    - matplotlib  *{{toolset.suffix}}
    - futures
    - ilastik-feature-selection   0.123

    # Python was already included via the headless package,
    # but we need to add it explicitly here due to a conda bug.
    - python      *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - ilastik-deps-pc-headless   *{{toolset.suffix}}
    - pyqt 4.11.3.99                     # [osx]
    - pyqt 4.11.3{{toolset.suffix}}      # [win or linux]
    - qimage2ndarray *{{toolset.suffix}}
    - vtk  5.10.1.99                     # [unix]
    - vtk  5.10.1{{toolset.suffix}}      # [win]
    - matplotlib  *{{toolset.suffix}}
    - futures
    - ilastik-feature-selection    0.123
    - python      *{{toolset.suffix}}
