about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-pc
  version: "1.1"

build:
  number: 5

requirements:

  run:
    - ilastik-deps-pc-headless
    - pyqt           4.11.4
    - qimage2ndarray
    - vtk            5.10.1.99 # [py2k]
    - futures                  # [py2k]
    - matplotlib

    # Python was already included via the headless package,
    # but we need to add it explicitly here due to a conda bug.
    - python
    