about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-pc
  version: "1.1"

requirements:
  build:
    - ilastik-deps-pc-headless 1.1 np19py27_0
    - pyqt 4.11.3 py27_1
    - qimage2ndarray 1.4 np19py27_0
    - vtk 5.10.1 with_pyqt
    - futures 2.2.0 py27_0
    - matplotlib 1.4.3 np19py27_1

  run:
    - ilastik-deps-pc-headless 1.1 np19py27_0
    - pyqt 4.11.3 py27_1
    - qimage2ndarray 1.4 np19py27_0
    - vtk 5.10.1 with_pyqt
    - futures 2.2.0 py27_0
    - matplotlib 1.4.3 np19py27_1
