about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-pc
  version: "1.1"

build:
  number: 3

requirements:

  run:
    - ilastik-deps-pc-headless
    - pyqt 4.11.3.99            # [osx]
    - pyqt 4.11.3               # [not osx]
    - qimage2ndarray
    - vtk 5.10.1.99
    - futures
    - matplotlib

    # Python was already included via the headless package,
    # but we need to add it explicitly here due to a conda bug.
    - python
    