{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: scipy
  version: "0.16.1{{toolset.suffix}}"

source:
  git_url: https://github.com/scipy/scipy.git
  git_tag: v0.16.1

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - mingw-for-msvc-build           # [win]
    - python 2.7.*{{toolset.suffix}}
    - numpy  >=1.10,*{{toolset.suffix}}
    - cython *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - mingw-for-msvc                 # [win]
    - python 2.7.*{{toolset.suffix}}
    - numpy  >=1.10,*{{toolset.suffix}}

about:
  home: www.scipy.org
  license: BSD
  summary: Scientific Library for Python
