package:
  name: pydvid
  version: !!str 0.1

source:
  git_url: https://github.com/janelia-flyem/pydvid
  git_tag: HEAD

requirements:
  build:
    - python
    - setuptools
    - jsonschema

  run:
    - python
    - numpy
    - jsonschema

test:
  # Python imports
  imports:
    - pydvid

about:
  home: http://janelia-flyem.github.io/pydvid
  license: BSD License
  summary: 'Simple client for retrieving volume cutout data from a DVID server as numpy arrays.'
