package:
  name: pydvid
  version: !!str 0.1

source:
  git_url: https://github.com/janelia-flyem/pydvid
  git_tag: HEAD

requirements:
  build:
    - python      2.7.9  3
    - setuptools  15.2   py27_0
    - jsonschema  2.4.0  0

  run:
    - python      2.7.9  3
    - numpy       1.9.2  py27_0
    - jsonschema  2.4.0  0

test:
  # Python imports
  imports:
    - pydvid

about:
  home: http://janelia-flyem.github.io/pydvid
  license: BSD License
  summary: 'Simple client for retrieving volume cutout data from a DVID server as numpy arrays.'
