{% import 'CONDA_ENVIRONMENT/toolset-info/config.yaml' as toolset %}

package:
  name: sip
  version: "4.16.9{{toolset.suffix}}"

source:
  fn:  sip-4.16.9.tar.gz
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.9/sip-4.16.9.tar.gz
  md5: 7a1dfff4e6fade0e4adee2c4e3d3aa9a

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}

about:
  home: http://www.riverbankcomputing.com/software/sip/
  license: PSF
  summary: Python extension module generator


