{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  # pure python
  name: ilastik-meta-devel
  version: master

build:
  number: 1

requirements:
  build:
    - {{toolset.build_requirement}}

  run:
    - {{toolset.run_requirement}}

