{% import 'CONDA_ENVIRONMENT/toolset-info/config.yaml' as toolset %}

package:
  name: mingw
  version: "4.7.2"

requirements:
  build:
    - {{toolset.build_requirement}}
    - emulate_c99   *{{toolset.suffix}}   # [win]

  run:
    - {{toolset.run_requirement}}
    - emulate_c99   *{{toolset.suffix}}   # [win]
