package:
  # pure python
  name: pep8
  version: "1.4.5"

source:
  fn:  pep8-1.4.5.tar.gz
  url: http://pypi.python.org/packages/source/p/pep8/pep8-1.4.5.tar.gz
  md5: 055dbd22ac5669232fdba752612e9686

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://pypi.python.org/pypi/pep8
  license: MIT
  summary: style guide checker
