{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  # pure python
  name: ilastik-meta
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/ilastik/ilastik-meta
  git_tag: 1.1.7

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - {{toolset.build_requirement}}  # FIXME: needed for dos-tools.bat
    - python
  run:
    - python
