package:
  name: ilastik-meta
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/ilastik/ilastik-meta
  git_tag: 1.1.7

build:
  number: 1
  string: 1_{{ environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - python
  run:
    - python
