{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: tornado
  version: "4.2.1{{toolset.suffix}}"

source:
  fn:  tornado-4.2.1.tar.gz
  url: https://pypi.python.org/packages/source/t/tornado/tornado-4.2.1.tar.gz
  md5: d523204389cfb70121bb69709f551b20

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - certifi
    - ssl_match_hostname

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - certifi
    - ssl_match_hostname

about:
  home: https://pypi.python.org/pypi/tornado
  license: Apache license
  summary: Python web framework and asynchronous networking library

