{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: scipy
  version: "0.16.0{{toolset.suffix}}"

source:
  fn:  scipy-0.16.0.tar.gz
  md5: eb95dda0f36cc3096673993a350cde77
  url: https://pypi.python.org/packages/source/s/scipy/scipy-0.16.0.tar.gz

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - mingw-for-msvc-build           # [win]
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - mingw-for-msvc                 # [win]
    - python 2.7.*{{toolset.suffix}}
    - numpy  *{{toolset.suffix}}

about:
  home: www.scipy.org
  license: BSD
  summary: Scientific Library for Python
