{% import TOOLSET_CONFIG as toolset %}

package:
  name: qt
  version: "4.8.6{{toolset.suffix}}"

build:
  number: 1
  detect_binary_files_with_prefix: true

  always_include_files:              # [win]
    - Library\bin\*                  # [win]
    - Qt4\imports\*                  # [win]
    - Qt4\include\*                  # [win]
    - Qt4\mkspecs\*                  # [win]
    - Qt4\plugins\*                  # [win]
    - Qt4\lib\*.lib                  # [win]
    - Qt4\lib\fonts\*                # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - qt-with-src  4.8.6{{toolset.suffix}} # [win]
    - jpeg     8d                    # [unix]
    - libtiff  4.0*                  # [unix]
    - libpng   1.6.17                # [unix]
    - freetype                       # [unix]
    - zlib                           # [unix]

  run:
    - {{toolset.run_requirement}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}
    - zlib     *{{toolset.suffix}}
