package:
  name: qt
  version: 4.8.6.99

source:
  git_url: https://github.com/qtproject/qt
  #git_tag: v4.8.6 # 682ed9df439481e1f8e8651c4aa06f1b455a2080
  git_tag: 445d29dbb8135944ff3a9283b7622de75d68e747

  patches:
    # This patch fixes ilastik crashes on OSX due to an ill-shaped ellipse
    - patches/qt4-osx-draw-ellipse.patch  # [osx]

    # This patch fixes crashes with modal dialogs on OSX:
    # https://bugreports.qt.io/secure/attachment/46537/QTBUG-40585-Rev3.patch
    - patches/QTBUG-40585-Rev3.patch  # [osx]
    
build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - visual-studio 11.0 # [win]
    - freetype
    - jpeg     8d          # [not win]
    - jpeg     1.2.1.99    # [win]
    - libtiff  4.0*        # [not win]
    - libtiff  4.0.1.99    # [win]
    - libpng   1.6.17      # [not win]
    - libpng   1.5.13      # [win]
    - zlib

  run:
    - visual-studio 11.0 # [win]
    - freetype
    - jpeg     8d          # [not win]
    - jpeg     1.2.1.99    # [win]
    - libtiff  4.0*        # [not win]
    - libtiff  4.0.1.99    # [win]
    - libpng   1.6.17      # [not win]
    - libpng   1.5.13      # [win]
    - zlib

  
