package:
  name: python-dateutil
  version: 2.4.2

source:
  fn:  python-dateutil-2.4.2.tar.gz
  url: https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.2.tar.gz
  md5: 4ef68e1c485b09e9f034e10473e5add2

requirements:
  build:
    - python 2.7.10 # [win]
    - six

  run:
    - python 2.7.10 # [win]
    - six

about:
  home: https://pypi.python.org/pypi/python-dateutil
  license: BSD
  summary: Extensions to the standard Python datetime module

