{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = true %}
{% else %}
  {% set WITH_SOLVERS = WITH_SOLVERS|int %}
{% endif %}

package:
  {% if WITH_SOLVERS %}
    name: ilastik-versions
  {% else %}
    name: ilastik-versions-no-solvers
  {% endif %}
    version: 1.2

build:
  number: 11

#
# In general, we don't specify exact version requirements in each sub-package.
# But this file tracks the versions of all packages used in the release.
requirements:
  run:
    - ann                       1.1.2     
    - armadillo                 6.500.5   
    #- blist                     1.3.6 # Only needed by deprecated operators     
    - boost                     1.55.0    
    #- cylemon                   1         
    - dlib                      18.16
    - decorator                 3.4.0
    - dpct                      1.1.post4
    - faulthandler              2.4       
    - fftw                      3.3.4     
    - freetype                  2.5.2     
    - futures                   3.0.2     
    - greenlet                  0.4.6     
    - h5py                      2.6.0     
    - hdf5                      1.8.16    
    - hytra                     1.1.1
    - iiboost                   0.2.post2       
    - ilastik-feature-selection 0.123.post9
    - ilastiktools              0.2       
    - ilastikrag                0.1.post12
    - itk-seg-conv-only         4.6.1     
    - jbig                      2.1
    - jpeg                      8d        
    - jsonschema                2.4.0     
    - lemon                     1.2.4     
    - libgcc                    4.8.5  1999 # [linux]
    - libgcc                    4.8.5  1    # [osx]
    - libpng                    1.6.17
    - libtiff                   4.0.6
    - libxml2                   2.9.0     
    - matplotlib                1.5.1     
    - mlpack                    1.0.8.99     

{% if WITH_SOLVERS %}
    - multi-hypotheses-tracking-with-gurobi 1.1.2
    - multi-hypotheses-tracking-with-cplex  1.1.2
{% endif %}

    - networkx                  1.11
    - nifty                     0.2.post257     py27_0_g968d496 # [unix]
    
{% if WITH_SOLVERS %}
    ###- nifty-with-cplex          0.2.post173 # [unix] # Not working, apparently.
    - nifty-with-gurobi         0.2.post257     py27_0_g968d496 # [unix]
{% endif %}

    - nose                      1.3.6     
    - numpy                     1.11.1     
    - opengm                    2.3.7.post29     
    - opengm-structured-learning-headers  2.3.4 np111py27_3_ga0797cd

{% if WITH_SOLVERS %}
    - opengm-with-cplex         2.3.7.post29 # [unix]
{% endif %}

    - openssl                   1.0.2j    
    - pandas                    0.18.1

{% if WITH_SOLVERS %}
    - pgmlink                   1.3       
{% endif %}

    - pillow                    3.0.0
    - pip                       6.1.1     
    - psutil                    2.2.1     
    - pyparsing                 2.0.3     
    - pyqt                      4.11.3    # [not osx]
    - pyqt                      4.11.3.99 # [osx]
    - python                    2.7.12     
    - python-dateutil           2.4.2     
    - pytz                      2015.4    
    - qimage2ndarray            1.4       
    - qt                        4.8.6    # [not osx]
    - qt                        4.8.6.99 # [osx]
    - readline                  6.2       
    - scikit-learn              0.17.1    
    - scikit-image              0.12.3
    - scipy                     0.17.0 # Can't use 0.17.1=np111py27_1 due to https://github.com/ContinuumIO/anaconda-issues/issues/899
    - setuptools                23.0.0      
    - sip                       4.16.5    
    - six                       1.9.0     
    - sqlite                    3.13.0
    # - tifffile                  0.9.2.post1 # Can't use the new version. See ilastik-build-conda/tifffile/meta.yaml
    - tifffile                  0.4.post2
    - tk                        8.5.18    
    - vigra                     1.11.0.post194
    - vtk                       5.10.1.99
    - wsdt                      0.2.post4
    - yapsy                     1.10.423  
    - zlib                      1.2.8     
    - xz                        5.0.5
