package:
  name: ilastik-versions
  version: 1.2

build:
  number: 2

#
# In general, we don't specify exact version requirements in each sub-package.
# But this file tracks the versions of all packages used in the release.
requirements:
  run:
    - ann                       1.1.2     
    - armadillo                 6.500.5   
    #- blist                     1.3.6 # Only needed by deprecated operators     
    - boost                     1.55.0    
    - cloog                     0.18.0    
    #- cylemon                   1         
    - dlib                      18.16
    - decorator                 3.4.0
    - faulthandler              2.4       
    - fftw                      3.3.4     
    - freetype                  2.5.2     
    - futures                   3.0.2     
    - gmp                       5.1.2     
    - greenlet                  0.4.6     
    - h5py                      2.5.0     
    - hdf5                      1.8.16    
    - iiboost                   0.2       
    - isl                       0.12.2    
    - itk-seg-conv-only         4.6.1     
    - jbig                      2.1
    - jpeg                      8d        
    - jsonschema                2.4.0     
    - lemon                     1.2.4     
    - libgcc                    4.8.5     
    - libpng                    1.6.17
    - libtiff                   4.0.6
    - libxml2                   2.9.0     
    - matplotlib                1.4.3     
    - mlpack                    1.0.8.99     
    - mpc                       1.0.1     
    - mpfr                      3.1.2     
    - networkx                  1.9.1
    - nose                      1.3.6     
    - numpy                     1.9.2     
    - opengm                    2.3.4     
    - openssl                   1.0.1k    
    - pgmlink                   1.3       
    - pillow                    3.0.0
    - pip                       6.1.1     
    - psutil                    2.2.1     
    - pyparsing                 2.0.3     
    - pyqt                      4.11.3    # [not osx]
    - pyqt                      4.11.3.99 # [osx]
    - python                    2.7.9     
    - python-dateutil           2.4.2     
    - pytz                      2015.4    
    - qimage2ndarray            1.4       
    - qt                        4.8.6    # [not osx]
    - qt                        4.8.6.99 # [osx]
    - readline                  6.2       
    - scikit-learn              0.16.1    
    - scikit-image              0.11.3
    - scipy                     0.15.1    
    - setuptools                16.0      
    - sip                       4.16.5    
    - six                       1.9.0     
    - sqlite                    3.8.4.1   
    - tifffile                  0.4.1
    - tk                        8.5.18    
    - vigra                     1.11.0.post28      
    - vtk                       5.10.1.99
    - yapsy                     1.10.423  
    - zlib                      1.2.8     
    - xz                        5.0.5
