package:
  name: ilastik-versions
  version: 1.1

build:
  number: 3

#
# In general, we don't specify exact version requirements in each sub-package.
# But this file tracks the versions of all packages used in the release.
requirements:
  run:
    - ann                       1.1.2     
    - armadillo                 4.000.2   # [unix]
    - armadillo                 4.320.0   # [win]
    #- blist                     1.3.6 # Only needed by deprecated operators     
    - boost                     1.55.0    
    - cloog                     0.18.0    # [unix]
    # - cylemon                   1         
    - cython                    0.23.99   # [win]
    - decorator                 3.4.0     # [unix]
    - decorator                 4.0.2     # [win]
    - faulthandler              2.4       
    - fftw                      3.3.4     
    - freetype                  2.5.2     # [unix]    
    - freetype                  2.4.11    # [win]    
    - futures                   3.0.2     # [unix]
    - futures                   2.1.3     # [win]
    - gmp                       5.1.2     # [unix]
    - greenlet                  0.4.6     # [unix]
    - greenlet                  0.4.7     # [win]
    - h5py                      2.5.0     
    - hdf5                      1.8.14    # [unix]
    - hdf5                      1.8.12.99 # [win]
    - iiboost                   0.1       
    - isl                       0.12.2    # [unix]
    - itk-seg-conv-only         4.6.1     
    - jpeg                      8d        # [unix]
    - jpeg                      1.2.1.99  # [win]
    - jsonschema                2.4.0     
    - lemon                     1.2.4     
    - libgcc                    4.8.4     # [unix]     
    - libpng                    1.6.17    # [unix]
    - libpng                    1.5.13    # [win]
    - libtiff                   4.0.2     # [unix]    
    - libtiff                   4.0.1.99  # [win]    
    - libxml2                   2.9.0     # [unix]
    - libxml2                   2.9.1     # [win]
    - matplotlib                1.4.3     # [unix]
    - matplotlib                1.4.3.99  # [win]
    - mingw                     4.7.2     # [win]   
    - mlpack                    1.0.8     
    - mpc                       1.0.1     # [unix]
    - mpfr                      3.1.2     # [unix]
    - networkx                  1.9.1     # [unix]
    - networkx                  1.1       # [win]
    - nose                      1.3.6     # [unix]
    - nose                      1.2.1     # [win]
    - numpy                     1.9.2     # [unix]
    - numpy                     1.7.0.99  # [win]
    - openblas                  0.2.5     # [win]     
    - opengm                    2.3.4     
    - openssl                   1.0.1k    # [unix]
    - openssl                   1.0.2a    # [win]
    - pgmlink                   1.2       
    - pillow                    2.7.0     # [unix]
    - pillow                    2.9.0     # [win]
    - pip                       6.1.1     # [unix]
    - pip                       7.1.0     # [win]
    - psutil                    2.2.1     # [unix]     
    - psutil                    2.1.1     # [win]     
    - pyparsing                 2.0.3     
    - pyqt                      4.11.3    # [linux]
    - pyqt                      4.11.3.99 # [osx]
    - pyqt                      4.11.3.99 # [win]
    - python                    2.7.9     # [unix]
    - python                    2.7.10    # [win]
    - python-dateutil           2.4.2     
    - pytz                      2015.4    # [unix]
    - pytz                      0.2.4     # [win]
    - qimage2ndarray            1.4       
    - qt                        4.8.6    # [linux]
    - qt                        4.8.6.99 # [osx]
    - qt                        4.8.6.99 # [win]
    - readline                  6.2      # [unix]
    - scikit-image              0.11.3
    - scikit-learn              0.16.1    
    - scipy                     0.15.1   # [unix]
    - scipy                     0.16.0   # [win]
    - setuptools                16.0     # [unix]
    - setuptools                18.2     # [win]
    - sip                       4.16.5   # [unix]
    - sip                       4.16.9   # [win]
    - six                       1.9.0     
    - sqlite                    3.8.4.1  # [unix]
    - sqlite                    3.8.11   # [win]
    - tifffile                  0.4.1
    - tk                        8.5.18   # [unix]
    - vigra                     1.10      
    - vtk                       5.10.1.99
    - yapsy                     1.10.423  
    - zlib                      1.2.8     
