package:
  name: opencv 
  version: "2.4.10.1"
  
source:
  fn: opencv-2.4.10.zip 
  url: http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.10/opencv-2.4.10.zip 
  md5: ec63952d3a3dff965d5fdde765926821  

build:
  number: 1
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.2.99 # [linux]
    - gcc 4.8.2 # [osx]
    
  run:
    - libgcc

about:
  home: opencv.org 
  license: BSD (3-clause)
  summary: Open source computer vision C++ library
