{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: armadillo
  version: "4.000.2{{toolset.suffix}}" # [unix]
  version: "4.320.0{{toolset.suffix}}" # [win]

source:
  fn:  armadillo-4.000.2.tar.gz                                                # [unix]
  url: http://downloads.sourceforge.net/project/arma/armadillo-4.000.2.tar.gz  # [unix]
  md5: b2891c7b59b96337c154c5d961fd40fb                                        # [unix]

  fn:  armadillo-4.320.0.tar.gz                                                # [win]
  url: http://sourceforge.net/projects/arma/files/armadillo-4.320.0.tar.gz     # [win]
  md5: d174ebcb5bffde6c8da8f47f06147386                                        # [win]

  patches:  # [unix]
    - patches/use_atlas_lapack.diff  # [unix]

build:
  features:
    - {{toolset.short}}
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - mingw-for-msvc-build             # [win] (needed for MSYS patch)
    - openblas                         # [win]
    - hdf5  1.8.12{{toolset.suffix}}   # [win]
    
  run:
    - {{toolset.run_requirement}}
    # - libgcc                         # [unix]
    - openblas                         # [win]
    - hdf5  1.8.12{{toolset.suffix}}   # [win]

about:
  home: http://arma.sourceforge.net
  license: MIT
  summary: Armadillo C++ Linear Algebra library
