package:
  # pure python
  name: pytz
  version: "2015.4"

source:
  fn:  pytz-2015.4.tar.bz2
  url: https://pypi.python.org/packages/source/p/pytz/pytz-2015.4.tar.bz2
  md5: 39f7375c4b1fa34cdcb4b4765d08f817

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://pypi.python.org/pypi/pytzpure
  license: GPL2
  summary: World timezone definitions
