package:
  name: pbr
  version: 1.6.0

source:
  fn:  pbr-1.6.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pbr/pbr-1.6.0.tar.gz
  md5: a9a0fc1c8ecabdf057eef5ff98d1ea71

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: https://pypi.python.org/pypi/pbr
  license: Apache Software License
  summary: Python Build Reasonableness

