{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: python
  version: "2.7.10{{toolset.suffix}}"

source:
  fn:  Python-2.7.10.tgz
  url: https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
  md5: d7547558fd673bd9d38e2108c6b42521

build:
  track_features:
    - {{toolset.short}}
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - perl    active_state           # [win]
    - bzip2-src-for-python           # [win]
    - openssl-src-for-python         # [win]
    - nasm                           # [win]
    - sqlite-src-for-python          # [win]

  run:
    - {{toolset.run_requirement}}

about:
  home: https://www.python.org/
  license: Python Software Foundation
  summary: The Python Interpreter
