package:
  name: python
  version: "2.7.10"

source:
  fn: Python-2.7.10.tgz
  url: https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
  md5: d7547558fd673bd9d38e2108c6b42521

requirements:
  build:
    - visual-studio 11.0  # [win]

  run:
    - visual-studio 11.0  # [win]

about:
  home: https://www.python.org/
  license: Python Software Foundation
  summary: The Python Interpreter