package:
  # pure python
  name: patsy
  version: "0.4.1dev"

source:
  git_url: https://github.com/pydata/patsy.git
  git_tag: 0c06192ce857f5638475092fedad11d67f323795

requirements:
  build:
    - python
    - numpy
    - six
    - setuptools

  run:
    - python
    - numpy
    - six

test:
  imports:
      - patsy

about:
  home: https://patsy.readthedocs.org/
  license: BSD
  summary: Describing statistical models using symbolic formulas
