{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: pillow
  version: "2.9.0{{toolset.suffix}}"

source:
  fn:  Pillow-2.9.0.tar.gz
  url: https://pypi.python.org/packages/source/P/Pillow/Pillow-2.9.0.tar.gz
  md5: 46f1729ece27981d54ec543ad5b37d14

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}
    - setuptools

  run:
    - {{toolset.run_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  4.0.*{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]
    - freetype *{{toolset.suffix}}

about:
  home: https://pypi.python.org/pypi/Pillow
  license: Standard PIL License (similar to BSD)
  summary: Python Imaging Library (Fork)

