package:
  # pure python
  name: pygments
  version: "2.0.2"

source:
  # fn:  Pygments-1.6.tar.gz
  # url: http://pypi.python.org/packages/source/P/Pygments/Pygments-1.6.tar.gz
  # md5: a18feedf6ffd0b0cc8c8b0fbdb2027b1
  fn:  Pygments-2.0.2.tar.gz
  url: https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.2.tar.gz
  md5: 238587a1370d62405edabd0794b3ec4a

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://pygments.org/
  license: BSD
  summary: Python syntax highlighter
