package:
  name: boost
  version: 1.55.0

source:
  fn: boost_1_55_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2

  patches:
    - 1.55.0_patches/6bb71fdd.diff  [osx]
    - 1.55.0_patches/e4bde20f.diff  [osx]
    - 1.55.0_patches/0005-Boost.S11n-include-missing-algorithm.patch  [osx]

build:
  number: 1

requirements:
  build:
    - gcc     4.8.2    5 # [osx]
    - gcc     4.8.2    linux_portable # [linux]
    - python  2.7.9    3
    - zlib    1.2.8    0

  run:
    - libgcc  4.8.4    1

about:
  home: http://www.boost.org/
  license: Boost-1.0

