package:
  name: boost
  version: 1.55.0

source:
  fn: boost_1_55_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2

  patches:
    - 1.55.0_patches/6bb71fdd.diff # [osx]
    - 1.55.0_patches/e4bde20f.diff # [osx]
    - 1.55.0_patches/0005-Boost.S11n-include-missing-algorithm.patch # [osx]

build:
  number: 4
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99  # [linux]
    - gcc 4.8.2     # [osx]
    - python        # [not win]
    - python 2.7.10 # [win]
    - zlib          # [not win]

  run:
    - libgcc # [not win]

about:
  home: http://www.boost.org/
  license: Boost-1.0

