{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: boost
  version: "1.60.0{{toolset.suffix}}"

source:
  fn: boost_1_60_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2

  patches:
    - 1.60.0.patch

build:
  features:
    - {{toolset.short}}
  number: 2
  detect_binary_files_with_prefix: true
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python    3.5
    - zlib                           # [unix]

  run:
    - {{toolset.run_requirement}}
    # - libgcc                         # [unix]

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: portable C++ libraries
