package:
  name: blist
  version: "1.3.6"

source:
  fn:  blist-1.3.6.tar.gz
  url: https://pypi.python.org/packages/source/b/blist/blist-1.3.6.tar.gz
  md5: a538f1a24b9191e3c40252e9397408a9

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - python 2.7.10                  # [win]
    - distribute

  run:
    - visual-studio {{ vc_version }} # [win]
    - python 2.7.10                  # [win]
    - distribute

about:
  home: https://pypi.python.org/pypi/blist
  license: BSD
  summary: a list-like type with better asymptotic performance and similar performance on small lists
