{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: blist
  version: "1.3.6{{toolset.suffix}}"

source:
  fn:  blist-1.3.6.tar.gz
  url: https://pypi.python.org/packages/source/b/blist/blist-1.3.6.tar.gz
  md5: a538f1a24b9191e3c40252e9397408a9

build:
  features:
    - {{toolset.short}}
    
requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - distribute

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}
    - distribute

about:
  home: https://pypi.python.org/pypi/blist
  license: BSD
  summary: a list-like type with better asymptotic performance and similar performance on small lists
