package:
  name: pickleshare
  version: 0.5

source:
  fn:  pickleshare-0.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pickleshare/pickleshare-0.5.tar.gz
  md5: 25337740507cb855ad58bfcf60f7710e

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: https://pypi.python.org/pypi/pickleshare
  license: MIT
  summary: Tiny 'shelve'-like database with concurrency support

