{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = true %}
{% else %}
  {% set WITH_SOLVERS = WITH_SOLVERS|int %}
{% endif %}

package:
  {% if WITH_SOLVERS %}
    name: ilastik-deps-multicut
  {% else %}
    name: ilastik-deps-multicut-no-solvers
  {% endif %}

    version: "1.2"

build:
  number: 1

requirements:

  run:
    - ilastik-deps-pc
    - ilastiktools
    - wsdt
    - ilastikrag
    - nifty
  {% if WITH_SOLVERS %}
    #- nifty-with-cplex # Not working right now
    - nifty-with-gurobi
  {% endif %}

about:
  summary: "A meta-package for building all the dependencies needed for multicut."

