package:
  name: qimage2ndarray
  version: !!str 1.4

source:
  fn: qimage2ndarray-1.4.tar.gz
  url: https://pypi.python.org/packages/source/q/qimage2ndarray/qimage2ndarray-1.4.tar.gz
  md5: 77359e694d498c958c90bcd3e3851d5d

requirements:
  build:
    - gcc         4.8.2   5 # [osx]
    - gcc         4.8.2   linux_portable # [linux]
    - python      2.7.9   3
    - setuptools  15.2    py27_0
    - numpy       1.9.2   py27_0
    - sip         4.16.5  py27_0
    - pyqt        4.11.3  py27_1

  run:
    - libgcc      4.8.4   1
    - python      2.7.9   3
    - numpy       1.9.2   py27_0
    - sip         4.16.5  py27_0
    - pyqt        4.11.3  py27_1

test:
  # Python imports
  imports:
    - qimage2ndarray

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD License
  summary: 'Conversion between QImages and numpy.ndarrays.'
