package:
  name: qimage2ndarray
  version: !!str 1.4

source:
  fn: qimage2ndarray-1.4.tar.gz
  url: https://pypi.python.org/packages/source/q/qimage2ndarray/qimage2ndarray-1.4.tar.gz
  md5: 77359e694d498c958c90bcd3e3851d5d

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99       # [linux]
    - gcc 4.8.2          # [osx]
    - visual-studio 11.0 # [win]
    - python             # [not win]
    - python 2.7.10      # [win]
    - setuptools
    - numpy              # [not win]
    - numpy    1.7.0.99  # [win]
    - sip
    - pyqt 4.11.3.99     # [osx or win]
    - pyqt 4.11.3        # [linux]

  run:
    - libgcc             # [not win]
    - visual-studio 11.0 # [win]
    - python             # [not win]
    - python 2.7.10      # [win]
    - numpy              # [not win]
    - numpy    1.7.0.99  # [win]
    - sip
    - pyqt 4.11.3.99     # [osx or win]
    - pyqt 4.11.3        # [linux]


# test:
  # # Python imports
  # FIXME: this doesn't work on Windows because LIBRARY_BIN is not in the PATH
  # imports:
    # - qimage2ndarray

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD License
  summary: 'Conversion between QImages and numpy.ndarrays.'
