{% import TOOLSET_CONFIG as toolset %}

package:
  name: qimage2ndarray
  version: "1.4{{toolset.suffix}}"

source:
  fn: qimage2ndarray-1.4.tar.gz
  url: https://pypi.python.org/packages/source/q/qimage2ndarray/qimage2ndarray-1.4.tar.gz
  md5: 77359e694d498c958c90bcd3e3851d5d

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python 2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - pyqt 4.11.3.99                   # [osx]
    - pyqt 4.11.3*{{toolset.suffix}}   # [linux or win]
    - setuptools
    - sip     *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    # - libgcc                         # [unix]
    - python 2.7.*{{toolset.suffix}}
    - numpy   *{{toolset.suffix}}
    - pyqt 4.11.3.99                   # [osx]
    - pyqt 4.11.3*{{toolset.suffix}}   # [linux or win]
    - sip     *{{toolset.suffix}}


test:
  # Python imports
  imports:
    - qimage2ndarray

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD License
  summary: 'Conversion between QImages and numpy.ndarrays.'
