package:
  name: qimage2ndarray
  version: !!str 1.4

source:
  fn: qimage2ndarray-1.4.tar.gz
  url: https://pypi.python.org/packages/source/q/qimage2ndarray/qimage2ndarray-1.4.tar.gz
  md5: 77359e694d498c958c90bcd3e3851d5d

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.5.99 # [linux]
    - gcc 4.8.5.99 # [osx]
    - python
    - setuptools
    - numpy
    - sip
    - pyqt 4.11.3.99            # [osx]
    - pyqt 4.11.3               # [not osx]

  run:
    - libgcc
    - python
    - numpy
    - sip
    - pyqt 4.11.3.99            # [osx]
    - pyqt 4.11.3               # [not osx]

test:
  # Python imports
  imports:
    - qimage2ndarray

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD License
  summary: 'Conversion between QImages and numpy.ndarrays.'
