package:
  name: qimage2ndarray
  version: "1.6"

source:
  git_url: https://github.com/hmeine/qimage2ndarray
  git_tag: release-1.6

build:
  number: 0
  string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}

requirements:
  build:
    - python 2.7*|3.5*
    - python {{PY_VER}}*
    - numpy >=1.9

  run:
    - python {{PY_VER}}*
    - numpy >=1.9
    - pyqt

test:
  source_files:
    - test
  requires:
    - nose

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD License
  summary: 'Conversion between QImages and numpy.ndarrays.'
