{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: iiboost
  version: "0.1post2{{toolset.suffix}}"  # post1 since numpy was upgraded

source:
  git_url: https://github.com/cbecker/iiboost
  git_tag: 76140cd985ab301749395bb47cbc8f8d88cdd257 # master 2016/07/07
  patches:
    - isnan.patch  # [win]

build:
  features:
    - {{toolset.short}}
  number: 0
  detect_binary_files_with_prefix: true
  string: 0_g76140cd
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - itk-seg-conv-only  *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]

  run:
    # - libgcc                           # [unix]
    - {{toolset.run_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - itk-seg-conv-only  *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]

about:
  home: http://github.com/cbecker/iiboost
  license: GPLv3
  summary: Learning Context Cues for Synapse Segmentation
