package:
  name: iiboost
  version: 0.1

source:
  git_url: git://github.com/cbecker/iiboost.git
  git_tag: 437491b5257cce74f86977ed203e1ccb2a02bd5c # 2015-08-17

build:
  number: 3
  string: 3_g437491b
  detect_binary_files_with_prefix: true

requirements:  
  build:
    - gcc 4.8.2.99       # [linux]
    - gcc 4.8.2          # [osx]
    - visual-studio 11.0 # [win]
    - python             # [unix]
    - python  2.7.10     # [win]
    - numpy              # [unix]
    - numpy    1.7.0.99  # [win]
    - itk-seg-conv-only
    - jpeg               # [unix]
    - jpeg     1.2.1.99  # [win]
    - libtiff            # [unix]
    - libtiff  4.0.1.99  # [win]
    - libpng   1.6.17    # [unix]
    - libpng   1.5.13    # [win]

  run:
    - libgcc             # [unix]
    - visual-studio 11.0 # [win]
    - python             # [unix]
    - python  2.7.10     # [win]
    - numpy              # [unix]
    - numpy    1.7.0.99  # [win]
    - itk-seg-conv-only
    - jpeg               # [unix]
    - jpeg     1.2.1.99  # [win]
    - libtiff            # [unix]
    - libtiff  4.0.1.99  # [win]
    - libpng   1.6.17    # [unix]
    - libpng   1.5.13    # [win]

test:           # [unix]
  imports:      # [unix]
    - iiboost   # [unix]

about:
  home: http://github.com/cbecker/iiboost
  license: GPLv3
  summary: Learning Context Cues for Synapse Segmentation
