package:
  name: iiboost
  version: "0.1"

source:
  git_url: git://github.com/cbecker/iiboost.git
  git_tag: 437491b5257cce74f86977ed203e1ccb2a02bd5c # 2015-08-17

build:

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  number: 3
  detect_binary_files_with_prefix: true
  string: 3_g437491b                 # [unix]
  string: 3_g437491b_{{ vc }}        # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]
    - gcc 4.8.2.99                   # [linux]
    - gcc 4.8.2                      # [osx]
    - python   2.7.*
    - numpy                          # [unix]
    - numpy    1.7.0                 # [win]
    - itk-seg-conv-only
    - jpeg                           # [unix]
    - jpeg     1.2.1                 # [win]
    - libtiff                        # [unix]
    - libtiff  4.0.1                 # [win]
    - libpng   1.6.17                # [unix]
    - libpng   1.5.13                # [win]

  run:
    - libgcc                         # [unix]
    - visual-studio {{ vc_version }} # [win]
    - python   2.7.*
    - numpy                          # [unix]
    - numpy    1.7.0                 # [win]
    - itk-seg-conv-only
    - jpeg                           # [unix]
    - jpeg     1.2.1                 # [win]
    - libtiff                        # [unix]
    - libtiff  4.0.1                 # [win]
    - libpng   1.6.17                # [unix]
    - libpng   1.5.13                # [win]

test:
  imports:
    - iiboost

about:
  home: http://github.com/cbecker/iiboost
  license: GPLv3
  summary: Learning Context Cues for Synapse Segmentation
