{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: iiboost
  version: "0.1post1{{toolset.suffix}}"  # post1 since numpy was upgraded

source:
  git_url: git://github.com/cbecker/iiboost.git
  git_tag: 437491b5257cce74f86977ed203e1ccb2a02bd5c # 2015-08-17

build:
  features:
    - {{toolset.short}}
  number: 3
  detect_binary_files_with_prefix: true
  string: 3_g437491b

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                   # [linux]
    # - gcc 4.8.2                      # [osx]
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - itk-seg-conv-only  *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]

  run:
    # - libgcc                           # [unix]
    - {{toolset.run_requirement}}
    - python   2.7.*{{toolset.suffix}}
    - numpy    *{{toolset.suffix}}
    - itk-seg-conv-only  *{{toolset.suffix}}
    - jpeg     8d                      # [unix]
    - jpeg     1.2.*{{toolset.suffix}} # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                  # [unix]
    - libpng   1.5.*{{toolset.suffix}} # [win]

test:
  imports:
    - iiboost

about:
  home: http://github.com/cbecker/iiboost
  license: GPLv3
  summary: Learning Context Cues for Synapse Segmentation
