package:
  name: iiboost
  version: 0.1

source:
  git_url: git://github.com/cbecker/iiboost.git
  git_tag: 437491b5257cce74f86977ed203e1ccb2a02bd5c # 2015-08-17

build:
  number: 3
  string: 3_g437491b
  detect_binary_files_with_prefix: true

requirements:  
  build:
    - gcc 4.8.5.99 # [linux]
    - gcc 4.8.2 # [osx]
    - python
    - numpy
    - itk-seg-conv-only
    - jpeg
    - libtiff
    - libpng 1.6.17

  run:
    - libgcc
    - python
    - numpy
    - itk-seg-conv-only
    - jpeg
    - libtiff
    - libpng 1.6.17

test:
  imports:
    - iiboost

about:
  home: http://github.com/cbecker/iiboost
  license: GPLv3
  summary: Learning Context Cues for Synapse Segmentation
