package:
  name: iiboost
  version: 0.1

source:
  # TODO: Change back to cbecker/iiboost after he accepts my pull request.
  #git_url: git://github.com/cbecker/iiboost.git
  git_url: git://github.com/stuarteberg/iiboost.git
  git_tag: HEAD

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:  
  build:
    - gcc 4.8.2.99 # [linux]
    - gcc 4.8.2 # [osx]
    - python
    - numpy
    - itk-seg-conv-only
    - jpeg
    - libtiff
    - libpng

  run:
    - libgcc
    - python
    - numpy
    - itk-seg-conv-only
    - jpeg
    - libtiff
    - libpng

test:
  imports:
    - iiboost

about:
  home: http://github.com/cbecker/iiboost
  license: GPLv3
  summary: Learning Context Cues for Synapse Segmentation
