{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: libpng
  version: "1.5.13{{toolset.suffix}}"

source:
    fn:  libpng-1.5.13.tar.gz
    md5: 9c5a584d4eb5fe40d0f1bc2090112c65
    url: http://sourceforge.net/projects/libpng/files/libpng15/older-releases/1.5.13/libpng-1.5.13.tar.gz

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - zlib   *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - zlib   *{{toolset.suffix}}

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: libpng license (similar to BSD)
  summary: PNG image format I/O
