package:
  name: mitoolbox
  version: "2.1.2"

source:
  git_url: https://github.com/Craigacp/MIToolbox
  git_tag: "v2.1.2"

build:
  number: 0

# No requirements! :-)
# No tests! :-(

about:
  home: https://github.com/Craigacp/MIToolbox
  license: BSD
  summary: 'Mutual Information functions for C and MATLAB'
