{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: dlib
  version: "18.16{{toolset.suffix}}"

source:
  fn: dlib-18.16.tar.bz2
  url: http://downloads.sourceforge.net/project/dclib/dlib/v18.16/dlib-18.16.tar.bz2
  md5: e9e5449bc25370afce2d254327afac99

  patches:
    - CMakeLists.txt.patch   # Add 'install' step
    - CMakeLists.txt.patch_2 # Allow linking external jpeg, even on Mac OSX

build:
  number: 0
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - libpng   *{{toolset.suffix}}
    - jpeg     *{{toolset.suffix}}
    - sqlite   *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - libpng   *{{toolset.suffix}}
    - jpeg     *{{toolset.suffix}}

about:
  home: http://dlib.net
  license: Boost
  summary: Dlib is a general purpose cross-platform C++ library designed using contract programming and modern C++ techniques.
