package:
  # pure python
  name: pytest
  version: "2.8.7"

source:
  fn:  pytest-2.8.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest/pytest-2.8.7.tar.gz
  md5: 685e2137062c9821b1b74a4814795514

requirements:
  build:
    - python
    - colorama
    - py
    - setuptools

  run:
    - python
    - colorama
    - py

about:
  home: https://pypi.python.org/pypi/pytest
  license: MIT
  summary: simple powerful testing with Python
