{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: statsmodels
  version: "0.6.1{{toolset.suffix}}"

source:
  git_url: https://github.com/statsmodels/statsmodels.git
  git_tag: v0.6.1

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  features:
    - {{toolset.short}}

requirements:
  build:
    - python     *{{toolset.suffix}}
    - cython     *{{toolset.suffix}}
    - numpy      *{{toolset.suffix}}
    - scipy      *{{toolset.suffix}}
    - matplotlib *{{toolset.suffix}}
    - pandas     *{{toolset.suffix}}
    - setuptools

  run:
    - python     *{{toolset.suffix}}
    - numpy      *{{toolset.suffix}}
    - scipy      *{{toolset.suffix}}
    - matplotlib *{{toolset.suffix}}
    - pandas     *{{toolset.suffix}}
    - patsy

test:
  imports:
    - statsmodels

about:
  home: http://www.statsmodels.org/stable/index.html
  license: BSD
  summary: Statistical computations and models for SciPy
