{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: pyzmq
  version: "14.3.1{{toolset.suffix}}"

source:
  fn:  pyzmq-14.3.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzmq/pyzmq-14.3.1.tar.gz
  md5: 7196b4a6fbf98022f17ffa924be3d68d

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python 2.7.*{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python 2.7.*{{toolset.suffix}}

about:
  home: https://pypi.python.org/pypi/pyzmq
  license: BSD
  summary: Python bindings for the ZeroMQ Messaging Library
