package:
  name: pyzmq
  version: 14.3.1

source:
  fn:  pyzmq-14.3.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzmq/pyzmq-14.3.1.tar.gz
  md5: 7196b4a6fbf98022f17ffa924be3d68d

requirements:
  build:
    - python 2.7.10 # [win]

  run:
    - python 2.7.10 # [win]

about:
  home: https://pypi.python.org/pypi/pyzmq
  license: BSD
  summary: Python bindings for the ZeroMQ Messaging Library

