package:
  name: vtk
  version: "5.10.1.99"

source:
  url: http://www.vtk.org/files/release/5.10/vtk-5.10.1.tar.gz [not win]
  fn: vtk-5.10.1.tar.gz                     # [not win]
  md5: 264b0052e65bd6571a84727113508789     # [not win]

  #fn: VTK-5.10.1.win32-py2.6.exe           # [win32 and py26]
  #fn: VTK-5.10.1.win-amd64-py2.6.exe       # [win64 and py26]
  #fn: VTK-5.10.1.win32-py2.7.exe           # [win32 and py27]
  #fn: VTK-5.10.1.win-amd64-py2.7.exe       # [win64 and py27]

  patches:
    - osx_patches/no-gc.diff

build:
  number: 7
  string: with_pyqt_{{PKG_BUILDNUM}}

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - python
    - pyqt 4.11.3.99            # [osx]
    - pyqt 4.11.3               # [not osx]
    - jpeg
    - libpng >=1.6.27
    - libtiff
    - zlib
    - libxml2

  run:
    - libgcc # [linux]
    - python
    - jpeg
    - libpng >=1.6.27,<1.7
    - libtiff
    - zlib
    - libxml2

test:
  requires:
    - pyqt 4.11.3.99            # [osx]
    - pyqt 4.11.3               # [not osx]

  commands:
    - vtkpython -h # [unix]

  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD
