{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: vtk
  version: "5.10.1{{toolset.suffix}}"

source:
  url: http://www.vtk.org/files/release/5.10/vtk-5.10.1.tar.gz
  fn:  vtk-5.10.1.tar.gz
  md5: 264b0052e65bd6571a84727113508789

  patches:                     # [osx]
    - osx_patches/no-gc.diff   # [osx]

build:
  features:
    - {{toolset.short}}
  number: 5
  string: 5_with_pyqt
  detect_binary_files_with_prefix: true
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    # - gcc 4.8.2.99                        # [linux]
    - python  2.7.*{{toolset.suffix}}
    - qt-with-src 4.8.*{{toolset.suffix}} # [win]
    - pyqt 4.11.3{{toolset.suffix}}       # [linux or win]
    - pyqt 4.11.3.99                      # [osx]
    - jpeg     8d                         # [unix]
    - jpeg     1.2.*{{toolset.suffix}}    # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                     # [unix]
    - libpng   1.5.*{{toolset.suffix}}    # [win]
    - hdf5     1.8.*{{toolset.suffix}}    # [win]
    - freetype *{{toolset.suffix}}        # [win]
    - zlib     *{{toolset.suffix}}
    - libxml2  *{{toolset.suffix}}

  run:
    # - libgcc                              # [unix]
    - {{toolset.run_requirement}}
    - python  2.7.*{{toolset.suffix}}
    - pyqt 4.11.3{{toolset.suffix}}       # [linux or win]
    - pyqt 4.11.3.99                      # [osx]
    - jpeg     8d                         # [unix]
    - jpeg     1.2.*{{toolset.suffix}}    # [win]
    - libtiff  *{{toolset.suffix}}
    - libpng   1.6.17                     # [unix]
    - libpng   1.5.*{{toolset.suffix}}    # [win]
    - hdf5     1.8.*{{toolset.suffix}}    # [win]
    - freetype *{{toolset.suffix}}        # [win]
    - zlib     *{{toolset.suffix}}
    - libxml2  *{{toolset.suffix}}

# test:
  # requires:
    # - pyqt 4.11.3.99     # [osx]
    # - pyqt 4.11.3        # [linux or win]

  # commands:
    # - vtkpython -h

  # imports:
    # - vtk

about:
  home: http://www.vtk.org/
  license: BSD

