package:
  name: vtk
  version: "5.10.1.99"

source:
  url: http://www.vtk.org/files/release/5.10/vtk-5.10.1.tar.gz
  fn:  vtk-5.10.1.tar.gz
  md5: 264b0052e65bd6571a84727113508789

  patches:                     # [osx]
    - osx_patches/no-gc.diff   # [osx]

build:
  number: 5
  string: with_pyqt_5
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99       # [linux]
    - visual-studio 11.0 # [win]
    - python             # [unix]
    - python  2.7.10     # [win]
    - pyqt 4.11.3        # [linux]
    - pyqt 4.11.3.99     # [osx or win]
    - jpeg               # [unix]
    - jpeg     1.2.1.99  # [win]
    - libtiff            # [unix]
    - libtiff  4.0.1.99  # [win]
    - libpng   1.6.17    # [unix]
    - libpng   1.5.13    # [win]
    - zlib
    - libxml2
    - hdf5     1.8.12    # [win]
    - freetype           # [win]

  run:
    - libgcc             # [unix]
    - visual-studio 11.0 # [win]
    - python             # [unix]
    - python  2.7.10     # [win]
    - pyqt 4.11.3        # [linux]
    - pyqt 4.11.3.99     # [osx or win]
    - jpeg               # [unix]
    - jpeg     1.2.1.99  # [win]
    - libtiff            # [unix]
    - libtiff  4.0.1.99  # [win]
    - libpng   1.6.17    # [unix]
    - libpng   1.5.13    # [win]
    - zlib
    - libxml2
    - hdf5     1.8.12    # [win]
    - freetype           # [win]

# test:
  # requires:
    # - pyqt 4.11.3.99     # [osx]
    # - pyqt 4.11.3        # [linux]

  # commands:
    # - vtkpython -h       # [unix]

  # imports:
    # - vtk                # [unix]

about:
  home: http://www.vtk.org/
  license: BSD
