package:
  name: jsoncpp
  version: "1.6.2"

source:
  git_url: git://github.com/open-source-parsers/jsoncpp.git
  git_tag: 1.6.2

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - python

  run:
    - libgcc

test:
  requires:
    - python

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: MIT
  summary: A C++ library for interacting with JSON.
