about:
  summary: "A meta-package for building all the dependencies needed for the minimal, headless version of pixel/object classification."

package:
  name: ilastik-deps-pc-headless
  version: "1.1"

build:
  number: 2

requirements:
  build:
    - python             # [unix]
    - python  2.7.10     # [win]
    - numpy    >=1.9     # [unix]
    - numpy    1.7.0.99  # [win]
    - vigra
    - h5py
    - tifffile
    - psutil
    - greenlet
    - yapsy
    - scikit-learn
    - scikit-image
    - faulthandler
    - jsonschema
    - nose

  run:
    - python             # [unix]
    - python  2.7.10     # [win]
    - numpy    >=1.9     # [unix]
    - numpy    1.7.0.99  # [win]
    - vigra
    - tifffile
    - h5py
    - psutil
    - blist
    - greenlet
    - yapsy
    - scikit-learn
    - scikit-image
    - faulthandler
    - jsonschema
    - nose
    #- blist # only needed by deprecated operators
    