about:
  summary: "A meta-package for building all the dependencies needed for the minimal, headless version of pixel/object classification."

package:
  name: ilastik-deps-pc-headless
  version: "1.1"

build:
  number: 2

requirements:
  build:
    - python
    - numpy
    - vigra
    - h5py
    - tifffile
    - psutil
    - blist
    - greenlet
    - yapsy
    - scikit-learn
    - scikit-image
    - faulthandler
    - jsonschema
    - nose

  run:
    - python
    - numpy
    - vigra
    - tifffile
    - h5py
    - psutil
    - blist
    - greenlet
    - yapsy
    - scikit-learn
    - scikit-image
    - faulthandler
    - jsonschema
    - nose
