about:
  summary: "A meta-package for building all the dependencies needed for the minimal, headless version of pixel/object classification."

package:
  name: ilastik-deps-pc-headless
  version: "1.1"

requirements:
  build:
    - python 2.7.9 3
    - numpy 1.9.2 py27_0
    - vigra 1.10 a590b5b # 2015-05-05
    - h5py 2.5.0 np19py27_0
    - psutil 2.2.1 py27_0
    - blist 1.3.6 py27_0
    - greenlet 0.4.6 py27_0
    - yapsy 1.10.423 py27_0
    - scikit-learn 0.16.1 np19py27_0
    - faulthandler 2.4 py27_0
    - jsonschema 2.4.0 py27_0
    - nose 1.3.6 py27_0

  run:
    - python 2.7.9 3
    - numpy 1.9.2 py27_0
    - vigra 1.10 a590b5b # 2015-05-05
    - h5py 2.5.0 np19py27_0
    - psutil 2.2.1 py27_0
    - blist 1.3.6 py27_0
    - greenlet 0.4.6 py27_0
    - yapsy 1.10.423 py27_0
    - scikit-learn 0.16.1 np19py27_0
    - faulthandler 2.4 py27_0
    - jsonschema 2.4.0 py27_0
    - nose 1.3.6 py27_0
