{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for the minimal, headless version of pixel/object classification."

package:
  name: ilastik-deps-pc-headless
  version: "1.1{{toolset.suffix}}"

build:
  features:
    - {{toolset.short}}
  number: 2

requirements:
  build:
    - python  2.7.*{{toolset.suffix}}
    - numpy    >=1.9                   # [unix]
    - numpy    1.7.*{{toolset.suffix}} # [win]
    - ilastik-exe  *{{toolset.suffix}} # [win]
    - vigra        *{{toolset.suffix}}
    - h5py         *{{toolset.suffix}}
    - tifffile     *{{toolset.suffix}}
    - psutil       *{{toolset.suffix}}
    - greenlet     *{{toolset.suffix}}
    - yapsy
    - scikit-learn *{{toolset.suffix}}
    - scikit-image *{{toolset.suffix}}
    - faulthandler *{{toolset.suffix}}
    - jsonschema
    - nose

  run:
    - python  2.7.*{{toolset.suffix}}
    - numpy    >=1.9                   # [unix]
    - numpy    1.7.*{{toolset.suffix}} # [win]
    - ilastik-exe  *{{toolset.suffix}} # [win]
    - vigra        *{{toolset.suffix}}
    - h5py         *{{toolset.suffix}}
    - tifffile     *{{toolset.suffix}}
    - psutil       *{{toolset.suffix}}
    - greenlet     *{{toolset.suffix}}
    - yapsy
    - scikit-learn *{{toolset.suffix}}
    - scikit-image *{{toolset.suffix}}
    - faulthandler *{{toolset.suffix}}
    - jsonschema
    - nose
    #- blist # only needed by deprecated operators
