package:
  name: libdvid-cpp
  version: "0.1"
  
source:
  git_url: git://github.com/janelia-flyem/libdvid-cpp.git
  git_tag: 4872b315e5bb1467bb7473bd284c754bae212675 # 2015-09-17

build:
  number: 14
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.5.99 # [linux]
    - gcc 4.8.5.99 # [osx]
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python
    - numpy
    
  run:
    - libgcc
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python
    - numpy

test:
  # Python imports
  imports:
    - libdvid

about:
  home: http://github.com/janelia-flyem/libdvid-cpp
  license: BSD (3-clause)
  summary: C++ library for accessing DVID's REST API 
