package:
  name: libdvid-cpp
  version: "0.1"
  
source:
  git_url: git://github.com/janelia-flyem/libdvid-cpp.git
  git_tag: bca4a5eb806e08075e8d9ea5cad3af2ff250343c # 2015-09-17

build:
  number: 13
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.5.99 # [linux]
    - gcc 4.8.5.99 # [osx]
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python
    - numpy
    
  run:
    - libgcc
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python
    - numpy

test:
  # Python imports
  imports:
    - libdvid

about:
  home: http://github.com/janelia-flyem/libdvid-cpp
  license: BSD (3-clause)
  summary: C++ library for accessing DVID's REST API 
