package:
  name: libdvid-cpp
  version: "0.1"
  
source:
  git_url: git://github.com/janelia-flyem/libdvid-cpp.git
  git_tag: 90264da2b3f7137639a843b3f00963684c97871c # 2015-10-21

build:
  {% set build_num = 18 %}
  number: {{ build_num }}

  #
  # We use NPY_VER here: You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: "np{{ environ.get('NPY_VER', '-NPY_VER-UNDEFINED-').replace('.', '') }}\
           py{{ environ.get('PY_VER').replace('.', '') }}\
           _{{ build_num }}\
           _g{{ environ.get('GIT_FULL_HASH', '')[:7] }}"
  
requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python 2.7*
    - numpy >=1.9,{{ environ.get('NPY_VER', '-NPY_VER-UNDEFINED-') }}*
    
  run:
    - libgcc
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python {{ environ.get('PY_VER') }}*
    - numpy {{ environ.get('NPY_VER') }}*

test:
  # Python imports
  imports:
    - libdvid

about:
  home: http://github.com/janelia-flyem/libdvid-cpp
  license: BSD (3-clause)
  summary: C++ library for accessing DVID's REST API 
