package:
  name: libdvid-cpp
  version: "0.1"
  
source:
  git_url: git://github.com/janelia-flyem/libdvid-cpp.git
  git_tag: 198e9e0e8ddceaf4b44a28426afbfe781acc0037 # 2015-10-09

build:
  number: 16
  string: 16_198e9e0
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python
    - numpy
    
  run:
    - libgcc
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python
    - numpy

test:
  # Python imports
  imports:
    - libdvid

about:
  home: http://github.com/janelia-flyem/libdvid-cpp
  license: BSD (3-clause)
  summary: C++ library for accessing DVID's REST API 
