package:
  name: libdvid-cpp
  version: "0.1"
  
source:
  git_url: git://github.com/janelia-flyem/libdvid-cpp.git
  git_tag: 90264da2b3f7137639a843b3f00963684c97871c # 2015-10-21

build:
  {% set build_num = 19 %}
  number: {{ build_num }}

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{CONDA_NPY[:]}}py{{CONDA_PY}}_{{build_num}}_g{{GIT_FULL_HASH[:7]}}
  
requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python 2.7*
    - numpy >=1.9,{{NPY_VER}}*
    
  run:
    - libgcc
    - boost 1.55.0
    - jsoncpp
    - lz4
    - jpeg
    - libpng 1.6.17
    - curl
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*

test:
  # Python imports
  imports:
    - libdvid

about:
  home: http://github.com/janelia-flyem/libdvid-cpp
  license: BSD (3-clause)
  summary: C++ library for accessing DVID's REST API 
