{% import '$CONDA_ENV_PATH/toolset-info/config.yaml' as toolset %}

package:
  name: pandas
  version: 0.17.0{{toolset.suffix}}

source:
  git_url: https://github.com/pydata/pandas.git
  git_tag: v0.17.0

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  features:
    - {{toolset.short}}

requirements:
  build:
    - python     *{{toolset.suffix}}
    - cython     *{{toolset.suffix}}
    - numpy      *{{toolset.suffix}}
    - setuptools
    - pytz
    - python-dateutil

  run:
    - python     *{{toolset.suffix}}
    - numpy      *{{toolset.suffix}}
    - python-dateutil
    - pytz

test:
  imports:
    - pandas

  #requires:
  #  - nose

  #commands:
  #  - nosetests --exe -A "not slow and not network and not disabled" pandas

about:
  home: http://pandas.pydata.org
  license: BSD
  summary: Python Data Analysis Library
