about:
  summary: "A meta-package for building all the dependencies needed for pixel/object classification and tracking."

package:
  name: ilastik-deps-tracking
  version: "1.1"

build:
  number: 1

requirements:
  run:
    - ilastik-deps-pc
    - pgmlink
