{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = 1 %}
{% endif %}
{% set WITH_SOLVERS = WITH_SOLVERS|int %}

package:
  {% if WITH_SOLVERS %}
    name: ilastik-deps-tracking
  {% else %}
    name: ilastik-deps-tracking-no-solvers
  {% endif %}

    version: "1.1"

build:
  number: 3

requirements:
  run:
    - ilastik-deps-pc
    - hytra
    - dpct
{% if WITH_SOLVERS %}
    - pgmlink
    - multi-hypotheses-tracking-with-gurobi 1.1.2
    - multi-hypotheses-tracking-with-cplex  1.1.2
{% endif %}

about:
  summary: "A meta-package for building all the dependencies needed for pixel/object classification and tracking."
