{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for pixel/object classification and tracking."

package:
  name: ilastik-deps-tracking
  version: "1.2{{toolset.suffix}}"

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - ilastik-deps-pc    *{{toolset.suffix}}
    - opengm             *{{toolset.suffix}}
    - opengm-with-cplex  *{{toolset.suffix}}
    - pgmlink-with-cplex *{{toolset.suffix}}

  run:
    - ilastik-deps-pc    *{{toolset.suffix}}
    - opengm             *{{toolset.suffix}}
    - opengm-with-cplex  *{{toolset.suffix}}
    - pgmlink-with-cplex *{{toolset.suffix}}
