{% import TOOLSET_CONFIG as toolset %}

about:
  summary: "A meta-package for building all the dependencies needed for pixel/object classification and tracking."

package:
  name: ilastik-deps-tracking
  version: "1.1{{toolset.suffix}}"

requirements:
  build:
    - ilastik-deps-pc  *{{toolset.suffix}}
    - pgmlink          *{{toolset.suffix}}

  run:
    - ilastik-deps-pc  *{{toolset.suffix}}
    - pgmlink          *{{toolset.suffix}}
