about:
  summary: "A meta-package for building all the dependencies needed for pixel/object classification and tracking."

package:
  name: ilastik-deps-tracking
  version: "1.1"

requirements:
  build:
    - ilastik-deps-pc 1.1 0
    - pgmlink 1.2 np19py27_3

  run:
    - ilastik-deps-pc 1.1 0
    - pgmlink 1.2 np19py27_3
