package:
  name: zlib
  version: "1.2.8"

source:
    fn:  zlib-1.2.8.tar.gz
    md5: 44d667c142d7cda120332623eab69f40
    url: http://zlib.net/zlib-1.2.8.tar.gz

{% set vc_version = environ.get('VISUALSTUDIOVERSION') %}  # [win]
{% set vc = 'vc'+vc_version[:-2] %}                        # [win]

build:
  string: {{ vc }}                   # [win]
  track_features:
    - {{ vc }}                       # [win]
  features:
    - {{ vc }}                       # [win]

requirements:
  build:
    - visual-studio {{ vc_version }} # [win]

  run:
    - visual-studio {{ vc_version }} # [win]

about:
  home: http://zlib.net/
  license: BSD
  summary: compression library
