package:
  name: zlib
  version: "1.2.8"

source:
    fn:  zlib-1.2.8.tar.gz
    md5: 44d667c142d7cda120332623eab69f40
    url: http://zlib.net/zlib-1.2.8.tar.gz

requirements:
  build:
    - visual-studio 11.0 # [win]

  run:
    - visual-studio 11.0 # [win]

about:
  home: http://zlib.net/
  license: BSD
  summary: compression library
