{% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: zlib
  version: "1.2.8{{toolset.suffix}}"

source:
    fn:  zlib-1.2.8.tar.gz
    md5: 44d667c142d7cda120332623eab69f40
    url: http://zlib.net/zlib-1.2.8.tar.gz

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}

  run:
    - {{toolset.run_requirement}}

about:
  home: http://zlib.net/
  license: BSD
  summary: compression library
