package:
  name: patchelf-bigfile
  version: 0.9

source:
  fn: patchelf-0.9.tar.gz
  url: http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
  md5: 3c265508526760f233620f35d79c79fc

  patches:
    # Replaces a single constant to avoid "maximum file size exceeded" error.
    - patches/patchelf.cc.patch

build:
  number: 0
  skip: true  # [not linux]

test:
  commands:
    - patchelf-bigfile --help

about:
  home: http://nixos.org/patchelf.html
  license: GPL 3
  summary: >
    A small utility to modify the dynamic linker and RPATH of ELF executables,
    slightly modified to allow absurdly large files to be patched.
    (See the patch in this recipe.)
