{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: numpy
  version: "1.10.1{{toolset.suffix}}"

source:
    fn:  numpy-1.10.1.tar.gz
    md5: 3fed2b50906bc19018cec5fa26168aa5
    url: http://downloads.sourceforge.net/project/numpy/NumPy/1.10.1/numpy-1.10.1.tar.gz

build:
  features:
    - {{toolset.short}}

requirements:
  build:
    - {{toolset.build_requirement}}
    - python     *{{toolset.suffix}}
    - setuptools
    - mingw-for-msvc-build                  # [win]
    - openblas   >=0.2.15{{toolset.suffix}} # [win]
    - fftw       *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python     *{{toolset.suffix}}
    - openblas   >=0.2.15{{toolset.suffix}} # [win]
    - fftw       *{{toolset.suffix}}

test:
  imports:
    - numpy

about:
  home: http://www.numpy.org/
  license: BSD
  summary: Python linear algebra
