{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: numpy
  version: "1.10.1{{toolset.suffix}}"

source:
  git_url: https://github.com/numpy/numpy.git
  git_tag: v1.10.1

build:
  features:
    - {{toolset.short}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - {{toolset.build_requirement}}
    - python     *{{toolset.suffix}}
    - cython     *{{toolset.suffix}}
    - setuptools
    - mingw-for-msvc-build                  # [win]
    - openblas   >=0.2.15{{toolset.suffix}} # [win]
    - fftw       *{{toolset.suffix}}

  run:
    - {{toolset.run_requirement}}
    - python     *{{toolset.suffix}}
    - openblas   >=0.2.15{{toolset.suffix}} # [win]
    - fftw       *{{toolset.suffix}}

test:
  imports:
    - numpy

about:
  home: http://www.numpy.org/
  license: BSD
  summary: Python linear algebra
