package:
  name: numpy
  version: "1.7.0.99"

source:
    fn:  numpy-1.7.0.tar.gz
    md5: 4fa54e40b6a243416f0248123b6ec332
    url: http://downloads.sourceforge.net/project/numpy/NumPy/1.7.0/numpy-1.7.0.tar.gz

requirements:
  build:
    - visual-studio 11.0 # [win]
    - python
    - openblas           # [win]

  run:
    - visual-studio 11.0 # [win]
    - python
    - openblas           # [win]

#test:
#  imports:
#    - numpy   # FIXME: doesn't work on Windows: %LIBRARY_BIN% not in PATH

about:
  home: http://www.numpy.org/
  license: BSD
  summary: Python linear algebra
