package:
  # pure python
  name: pyflakes
  version: "0.7"

source:
  fn:  pyflakes-0.7.tar.gz
  url: http://pypi.python.org/packages/source/p/pyflakes/pyflakes-0.7.tar.gz
  md5: 4cbe17be937684654eb29d9efab67b80

requirements:
  build:
    # FIXME: build broken
    - python

  run:
    - python

about:
  home: https://pypi.python.org/pypi/pyflakes
  license: MIT
  summary: passive checker of Python programs
